### DISCUSSION TITLE
"worker process {id} exited on signal 9" on very large file upload

### DISCUSSION THREAD

**Discussion by Matthias-vdE** [ZoeyVid/NPMplus#1168] [Q&A] [answered]
When uploading really big files (talking 5GB and larger) to Immich via NPM, the upload always gets cancelled at the very end. The only thing that is showing in the log is

```
2024-10-17T11:44:37.096387678Z 2024/10/17 13:44:37 [warn] 1991#1991: *1725 a client request body is buffered to a temporary file /usr/local/nginx/client_body_temp/0000000002 while reading request body, client: 94.X.X.X, server: immich.X.X, request: "POST /api/assets HTTP/1.1", host: "immich.X.X"

2024-10-17T12:18:08.594066739Z 2024/10/17 14:18:08 [alert] 1693#1693: worker process 1991 exited on signal 9
```

Smaller files are no problem. I have disabled AppSec because it was causing issues as well (https://github.com/ZoeyVid/NPMplus/discussions/1123) but this has now been resolved (simply by disabling AppSec alltogether.)

My compose file looks like this:

```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/opt/npm:/data"
    environment:
      - "TZ=Europe/Brussels" 
      - "NGINX_LOG_NOT_FOUND=true" 
      - "LOGROTATE=true" 
      - "LOGROTATIONS=7"
      - "GOA=true"
      - "CRT=36"
      - "IPRT=3"
      - "NGINX_DISABLE_PROXY_BUFFERING=true"

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8080:8080"
    environment:
      - "TZ=Europe/Brussels"
      - "COLLECTIONS=ZoeyVid/npmplus"
      - "LEVEL_FATAL=true"
      - "LEVEL_ERROR=true"
      - "LEVEL_WARN=true"
      - "LEVEL_INFO=false"
      - "LEVEL_DEBUG=false"
      - "LEVEL_TRACE=false"
    volumes:
      - "/opt/crowdsec/conf:/etc/crowdsec"
      - "/opt/crowdsec/data:/var/lib/crowdsec/data"
      - "/opt/npm/nginx:/opt/npm/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  geoipupdate:
    container_name: geoipupdate
    image: maxmindinc/geoipupdate:latest
    restart: always
    network_mode: bridge
    environment:
      - "TZ=Europe/Brussels"
      - "GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-City GeoLite2-ASN"
      - "GEOIPUPDATE_ACCOUNT_ID=REDACTED"
      - "GEOIPUPDATE_LICENSE_KEY=REDACTED"
      - "GEOIPUPDATE_FREQUENCY=24"
    volumes:
      - "/opt/npm/etc/goaccess/geoip:/usr/share/GeoIP"
```

I haved tested with both NGINX_DISABLE_PROXY_BUFFERING true and false but the result is the same.

My Host configuration is this:

![image](https://github.com/user-attachments/assets/d91bdf14-eae1-433d-adf9-45bd01a09e39)

![image](https://github.com/user-attachments/assets/dd6d90bb-0f7c-4a4b-a33a-7185a81b827c)

![image](https://github.com/user-attachments/assets/570d7705-4af4-4962-92d9-315ac6e480c2)

The proxy timeout should be plenty. I've also disable gzip and Brotli because I thought that might cause an issue but it makes no difference in having this on or off.

I'm not hitting the memory limit of my server either (I have 16GB)

![image](https://github.com/user-attachments/assets/5ae46066-a928-4bc1-ae01-7a17059a5d70)

Any ideas, suggestions, or other logs I can gather in order to troubleshoot would be great. Or some other advanced Host options that may help with uploading large files.

Thanks.
