### DISCUSSION TITLE
Crowdsec and Immich

### DISCUSSION THREAD

**Discussion by MaximumFish** [ZoeyVid/NPMplus#1241] [Q&A] [answered]
Hi,

I recently migrated from a working nginx-proxy-manager + crowdsec (+ cloudflare) install to NPMplus + crowdsec. I thought everything was working nicely but it turns out that local backups to Immich are now failing, which I'm pretty sure is due to Crowdsec, even when uploading on the LAN. Stupidly, I deleted the old stack with all its config so I'm not entirely sure what I'm missing (and I didn't take any notes!) but I think that when it was working it was thanks to the suggestions in this thread: https://github.com/immich-app/immich/discussions/3243

Alas it doesn't seem to help with npmplus and now I'm at a bit of a loss. Before I get too far into the weeds trying to bodge something together, has anybody got a working example that I can crib from?

Thanks in advance...

**Comment by Zoey2936** [comment]
any docker logs?

**Comment by Strana-Mechty** [comment]
If you open a console in portainer/use docker exec on the crowdsec container, what does `cscli decisions list` say?

If you're sure crowdsec is causing it you can always whitelist the local IP (something I recommend you always do to prevent embarassing lock-out situations or strange APIs that work over intranet anyway), should it disappear then it's confirmed, you might wanna see in the decisions list what rule got tripped and remove it from the crowdsec list.

https://doc.crowdsec.net/u/getting_started/post_installation/whitelists/

**Reply by Zoey2936** [reply]
?

**Reply by Strana-Mechty** [reply]
It sounds to me like crowdsec might be detecting a violation as a false-positive when using immitch. I'm experiencing the same thing but with modsec-CRS and services like gitea ("looks like you're opening a .git/.env file on that webserver 😄" ).

I don't have immitch however so it's a big fat guess to me.

**Reply by Zoey2936** [reply]
yes that's why logs are important, if it is a false positive then it would be visible in the log. But I must say, I never say crowdsec to overblock yeet

**Comment by MaximumFish** [comment]
My apologies, I am seeing these comments but it's been one of those days and I've not found a moment to investigate further. Thanks for your replies, I'll get back to you as soon as I can!

**Comment by MaximumFish** [comment]
OK, here we go:

```
2024/11/19 17:20:06 [warn] 80110#80110: *51203 a client request body is buffered to a temporary file /usr/local/nginx/client_body_temp/0000000050 while reading request body, client: 10.42.0.11, server: immich.example.com, request: "POST /api/assets HTTP/1.1", host: "immich.example.com"
2024/11/19 17:20:06 [error] 80110#80110: *51203 send() failed (32: Broken pipe), client: 10.42.0.11, server: immich.example.com, request: "POST /api/assets HTTP/1.1", host: "immich.example.com"
2024/11/19 17:20:06 [error] 80110#80110: *51203 [lua] crowdsec.lua:578: AppSecCheck(): Fallback because of err: broken pipe, client: 10.42.0.11, server: immich.example.com, request: "POST /api/assets HTTP/1.1", host: "immich.example.com"
2024/11/19 17:20:06 [error] 80110#80110: *51203 [lua] crowdsec.lua:651: Allow(): AppSec check: broken pipe, client: 10.42.0.11, server: immich.example.com, request: "POST /api/assets HTTP/1.1", host: "immich.example.com"
2024/11/19 17:20:06 [alert] 80110#80110: *51203 [lua] crowdsec.lua:718: Allow(): [Crowdsec] denied '10.42.0.11' with 'ban' (by appsec), client: 10.42.0.11, server: immich.example.com, request: "POST /api/assets HTTP/1.1", host: "immich.example.com"
```

Yes, I'm using a very non-standard local subnet but it falls within the 10.0.0.0/8 range that's (supposed to be) whitelisted in Crowdsec by default.

As mentioned above I added the suggested whitelistings from this post (https://github.com/immich-app/immich/discussions/3243#discussioncomment-8817870) which are like so:

```
name: crowdsecurity/immich-whitelists
description: "Whitelist false positive from Immich-api"
filter: "evt.Meta.service == 'http' && evt.Meta.log_type in ['http_access-log', 'http_error-log']"
whitelist:
  reason: "Whitelist false positive from Immich-api"
  expression:
   - evt.Meta.http_verb == 'POST' && evt.Meta.http_status == '403' && evt.Parsed.request contains '/asset/upload'
   - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '429' && evt.Parsed.request contains '/api/asset/thumbnail/'
   - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '200' && evt.Parsed.request contains '/api/asset/thumbnail/'
   - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '304' && evt.Parsed.request contains '/api/asset/thumbnail/'
   - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '404' && evt.Parsed.request contains '/api/asset/thumbnail/'
```

Though looking at the logs, maybe the API endpoint has changed from `/api/asset/<function>` to just `/api/assets`? Though I can't find any supporting comments about it in the Immich changelog. Or perhaps I just need to add that endpoint to the whitelist and keep the others there...

Thanks for your help, both. It's massively appreciated.

**Reply by Zoey2936** [reply]
whitelisting will not help.
can you please disable appsec in your crowdsec config file. just comment the lines mentioning appsec please and retry (also disable modsec)

**Reply by MaximumFish** [reply]
I don't know what I've managed to do but now Crowdsec is completely broken. I set the file in acquis.d to read:

```
filenames:
  - /opt/npm/nginx/access.log
labels:
  type: npmplus
---
source: docker
container_name:
 - npmplus
labels:
  type: npmplus
#---
#source: docker
#container_name:
# - npmplus
#labels:
#  type: modsecurity
#---
#listen_addr: 0.0.0.0:7422
#appsec_config: crowdsecurity/appsec-default
#name: appsec
#source: appsec
#labels:
#  type: appsec
```

But after doing that it tries to load but bombs out with messages like:

`level=fatal msg="crowdsec init: while loading scenarios: scenario loading failed: unable to load alert context: compilation of 'match.uri' context value failed: unknown name match (1:1)\n | match.uri\n | ^`

and 

`level=fatal msg="crowdsec init: while loading scenarios: scenario loading failed: unable to load alert context: compilation of 'match.method' context value failed: unknown name match (1:1)\n | match.method\n | ^`

I tried to undo the changes, completely removed the container, deleted all the local config files, even logged into the CS dashboard and removed the engine from there. Went right back to square one and tried to get it reinstalled from scratch (just crowsec, not npmplus itself) but it's still doing the same thing.

Fake edit: Deploying a new container with the `- COLLECTIONS=ZoeyVid/npmplus` line removed from the compose file allows crowdsec to load, but I guess it's not really doing anything useful like that. I just don't know what's going on at this point!
