### DISCUSSION TITLE
2024-11-25-r1

### DISCUSSION THREAD

**Discussion by Zoey2936** [ZoeyVid/NPMplus#1257] [Announcements]
**Note: NPMplus has its own place at Reddit since a few months: https://www.reddit.com/r/NPMplus (very empty there), but I still prefer reporting anything over GitHub to have anything at one place**

## What's Changed
- NOTE: Breaking changes in release 2024-10-21-r1, please read the last changelog here: https://github.com/ZoeyVid/NPMplus/releases/tag/2024-10-21-r1
- dep updates
- readme changes
- ACME_MUST_STAPLE and ACME_SERVER_TLS_VERIFY options (see compose.yaml)
- Stop GoAccess errors by @Sproglet in https://github.com/ZoeyVid/NPMplus/pull/1245
- close #965 by merging https://github.com/NginxProxyManager/nginx-proxy-manager/pull/4187
- merge upstream (only this PR was merged: https://github.com/NginxProxyManager/nginx-proxy-manager/pull/4179)
- fix updating streams (untested, but should work, if not please open an issue)
- Note: if you want NPMplus in your language, please see the readme on how to contribute a translation

### How to update
- NOTE: watchtwoer does NOT update NPMplus
- Read the changes above
- Pull the zoeyvid/npmplus:latest image
- apply possible changes that maybe effect you from above to your compose.yaml/NPMplus
- redeploy the compose stack
- report any issues you find

**Full Changelog**: https://github.com/ZoeyVid/NPMplus/compare/2024-11-02-r1...2024-11-25-r1

<hr /><em>This discussion was created from the release <a href='https://github.com/ZoeyVid/NPMplus/releases/tag/2024-11-25-r1'>2024-11-25-r1</a>.</em>

**Comment by Giuseppe-TD** [comment]
i get 
2024-11-25T21:34:41.468759696Z certbot: error: unrecognized arguments:  

2024-11-25T21:34:41.468762046Z 
2024-11-25T21:36:02.323820752Z 2024/11/25 22:36:02 [error] 6880#6880: connect() to [2a02:26f0:118::adde:f509]:80 failed (101: Network unreachable) while requesting certificate status, responder: e5.o.lencr.org, peer: [2a02:26f0:118::adde:f509]:80, certificate: "/data/tls/certbot/live/npm-240/fullchain.pem"

2024-11-25T21:36:04.469775095Z 2024/11/25 22:36:04 [error] 6880#6880: connect() to [2a02:26f0:118::adde:f509]:80 failed (101: Network unreachable) while requesting certificate status, responder: e6.o.lencr.org, peer: [2a02:26f0:118::adde:f509]:80, certificate: "/data/tls/certbot/live/npm-257/fullchain.pem"

2024-11-25T21:36:04.469816592Z 2024/11/25 22:36:04 [error] 6880#6880: connect() to [2a02:26f0:118::adde:f521]:80 failed (101: Network unreachable) while requesting certificate status, responder: e6.o.lencr.org, peer: [2a02:26f0:118::adde:f521]:80, certificate: "/data/tls/certbot/live/npm-257/fullchain.pem"

when try to create a new certificate (to remove must staple), i've tested with many websites i own, i've tried to use without the env but the error is the same :(

**Reply by Zoey2936** [reply]
sorry, but NPMplus has no influence on your network infrastructure

**Reply by Giuseppe-TD** [reply]
before the update was working :( i updated to disable the must staple error in firefox, and as you wrote on notes i should recreate certs, and not working, and my network is working, i'm connected to it 

the error is 
2024-11-25T21:33:53.642316716Z certificate. 

2024-11-25T21:33:53.642320081Z certbot: error: unrecognized arguments:  

2024-11-25T21:33:53.642323417Z 

and nothing more, like there's something interfere with it





this is my compose: 


```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/portainer/Files/AppData/Config/Nginx-Proxy/data:/data"
#      - "/var/www:/var/www" # optional, if you want to use it as webserver for html/php
      - "/portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt/renewal:/etc/letsencrypt"
    environment:
      - "TZ=Europe/Rome" # set timezone, required
      - "ACME_EMAIL=emailaddress"
      - "ACME_MUST_STAPLE=false"

      - "LOGROTATE=true" # Enables writing http access logs to /opt/npm/nginx/access.log, stream access logs to /opt/npm/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=2"

```
