### DISCUSSION TITLE
cant set the forward server to host name

### DISCUSSION THREAD

**Discussion by Alacard** [ZoeyVid/NPMplus#1378] [Q&A] [answered]
when setting up a new proxy host, your unable to use the server hostname for the destination, show error data/forward_host must match pattern "^(([^.]+\.)+[^.]+)|(\[[0-9a-f:]+\])$" when you try
![Untitled](https://github.com/user-attachments/assets/554968c7-3a04-40e3-9b8b-e96d2e5113f0)

**Comment by Zoey2936** [comment, marked as answer]
Containernames/hostnames are allowed again but not recommended.

An option would be to use static IPs.

I personally handle it like this:
I run NPMplus in network mode host and to connect to my containers I expose the needed ports of them like this "127.0.0.1:<host-port>:<port-inside-container>" and in npmplus I proxy to 127.0.0.1 with <host-port>. Through this I don't need static IPs and have no problem with DNS. Also, containers of different services can't talk to each other since they don't need to be in the same docker network so that NPMplus can talk to them (or NPMplus doesn't need to be in all docker networks). And the non docker services could connect to all containers anyway

**Reply by Cantello** [reply]
Thanks for that explanation! However, when I expose a port in my docker-compose.yml like this:
```
    ports:
      - 127.0.0.1:25600:25600
```
I get a `Bad Gateway` error when trying to access the proxied site. `curl 127.0.0.1:25600` directly on the machine results in the correct web page being delivered. What could be wrong here if it worked before (with explicit IP address given as the target).

edit: it works now (with the target as "container_name.network_name:port") except for the main admin UI. But this is probably a different issue.

**Reply by Zoey2936** [reply]
can you send me your compose.yaml please?

**Reply by Cantello** [reply]
> can you send me your compose.yaml please?

I just edited my response as it nearly works now (with the container_name instead of 127.0.0.1) but here's an excerpt from my docker-compose.yml:
```
networks:
  network:
    name: network

services:

  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - "/opt/npmplus:/data"
    environment:
      - "TZ=Europe/Berlin"
      - "ACME_EMAIL=email@somewhere.invalid"
      - "IPV4_BINDING=0.0.0.0"
      - "NPM_IPV4_BINDING=0.0.0.0"
    networks:
      - network

  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - /opt/komga:/config
      - /mnt/box:/data
    ports:
      - 127.0.0.1:25600:25600
    user: 1001:1001
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    networks:
      - network
```

One problem that remains (but is maybe unrelated to this issue) is that I can set proxies to all other containers but not for npm+'s admin UI. When setting the network_mode to host it does not work at all, when set to bridge and the relevant ports are exposed, I can access the admin panel but only with the correct external IP address, not with the hostname (CNAME in the DNS set to the A with the IP address). Otherwise it results in an error (`Error code: [MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT]`) and `curl auth.domain.com:81` results in a "301 moved permanently". I have no idea why npm is not proxying correctly or not serving the correct SSL certificate. The logs do not show anything unusual. Can the logs somehow be set to debug mode?
