### DISCUSSION TITLE
All configs gone after `docker compose pull`

### DISCUSSION THREAD

**Discussion by lkd70** [ZoeyVid/NPMplus#1417] [Q&A] [answered]
After running `docker compose pull` and starting up the container, all the prior configs are gone from db, including users. The database is seamingly wiped clean.

I have a backup of the previous state, so if you require any information from either the original or new state I can provide this.

Images:
```
REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
zoeyvid/npmplus          latest    82e47e2b298e   12 days ago    246MB
crowdsecurity/crowdsec   latest    a11b3b2fee61   8 weeks ago    347MB
zoeyvid/npmplus          <none>    f06d6525d1a6   3 months ago   244MB
crowdsecurity/crowdsec   <none>    8b89fde39672   4 months ago   279MB
zoeyvid/npmplus          <none>    4ae49534842a   5 months ago   209MB
```

Log (seems related?):
```
npmplus   | [Global   ] › ℹ  info      Using Sqlite: /data/npmplus/database.sqlite
npmplus   | 2025/01/23 20:52:09 [error] 692#692: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.201, server: _, request: "GET /api/users/me?expand=permissions HTTP/2.0", upstream: "http://127.0.0.1:48681/users/me?expand=permissions", host: "10.0.0.100:81", referrer: "https://10.0.0.100:81/"
npmplus   | [Migrate  ] › ℹ  info      Current database version: none
npmplus   | [Migrate  ] › ℹ  info      [change_incoming_port_to_string] Migrating Up...
npmplus   | [Migrate  ] › ℹ  info      [change_incoming_port_to_string] stream Table altered
npmplus   | [Migrate  ] › ℹ  info      [regenerate_default_host] Migrating Up...
```

docker-compose.yml:
```yaml
root@NPM:~# cat docker-compose.yml
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: always
    network_mode: host
    volumes:
      - "/root/data:/data"
      - "/root/letsencrypt:/etc/letsencrypt"
      - "/root/goaccess/goaccess.conf:/goaccess/goaccess.conf"
      #- "/var/www:/var/www" # optional, if you want to use it as webserver for html/php
    environment:
      - "TZ=Europe/London"
      - "GOA=true"
      - "NGINX_404_REDIRECT=true"
      - "LOGROTATE=true"
      - "LOGROTATIONS=7"
      - "GOA_PORT=92"
      - "GOA_LISTEN_LOCALHOST=true"
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8383:8383"
    environment:
      - "TZ=Europe/London"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/opt/crowdsec/conf:/etc/crowdsec"
      - "/opt/crowdsec/data:/var/lib/crowdsec/data"
      - "/opt/npm/nginx:/opt/npm/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
