### DISCUSSION TITLE
Getting wierd random erros from Crowdsec in terminal

### DISCUSSION THREAD

**Discussion by DJKatastrof** [ZoeyVid/NPMplus#1449] [Q&A] [answered]
Getting strange errors in my crowdsec container. 
Compose.yaml file 

```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - ./npmplus:/data
      #- "/var/www:/var/www" 
    environment:
      - TZ=Europe/Stockholm
      - ACME_EMAIL=user@redacted.com
      - INITIAL_ADMIN_EMAIL=admin@redacted.com
      - INITIAL_ADMIN_PASSWORD=redacted
      - LOGROTATE=true

  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - 127.0.0.1:7422:7422
      - 127.0.0.1:8080:8080
    environment:
      - TZ=Europe/Stockholm # needs to be changed
      - COLLECTIONS=ZoeyVid/npmplus
    volumes:
      - ./npmplus/crowdsec/conf:/etc/crowdsec
      - ./npmplus/crowdsec/data:/var/lib/crowdsec/data
      - ./npmplus/nginx:/opt/npmplus/nginx:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

![image](https://github.com/user-attachments/assets/4162219f-ad72-49e3-bc7b-b8fd7a6934b5)

![image](https://github.com/user-attachments/assets/6f0f24aa-19d6-488b-bcec-45d547115a67)
