### DISCUSSION TITLE
Can't reach the admin interface

### DISCUSSION THREAD

**Discussion by MinecollYT** [ZoeyVid/NPMplus#1463] [Q&A] [answered]
Hello!

I migrated from the normal nginx proxy manager and so far everything works without any issues. Before the upgrade I accessed the admin interface via proxy.<our domain> and it worked fine. After the migration, I have to use our internal ip to open the admin interface (https://10.0.0.6:81/).

The server on which the docker container runs has two ips: 10.0.0.6 and 10.10.0.5 - I've tried to switch out the docker container name for both of them, but sadly this didn't work. Is this some kind of safety feature to prevent loops?

This is the current config inside the interface (LGS-Proxy is the name of the docker container):
![image](https://github.com/user-attachments/assets/67832afb-9cda-4eab-9cf1-589ca8ea2f8b)

docker-compose
```
networks:
  proxy_lgs:
    driver: bridge
    name: proxy_lgs
    
services:
  npmplus:
    container_name: LGS-Proxy
    image: 'docker.io/zoeyvid/npmplus:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - proxy_lgs
    volumes:
      - ./data:/data
    environment:
      - "TZ=Europe/Berlin"
```
