### DISCUSSION TITLE
Help on websites

### DISCUSSION THREAD

**Discussion by Giuseppe-TD** [ZoeyVid/NPMplus#1538] [Q&A] [answered]
I have several websites/proxy hosts (50) and I have some of them joomla websites for my clients, I'm starting a slowliness on the server response time, 800~ when on page speed should be less than 600, I started to notice it few updates ago, so I'm looking for a solution, should I maybe disable proxy buffering ? Or maybe add some variables to improve the performance ? 

This happen from 2/3 months ago before the response time was good

I'm using crowdsec .. this can be a problem?

**Comment by Zoey2936** [comment]
can you maybe tell more about your setup? hardware setup and network setup

**Comment by Giuseppe-TD** [comment]
This is my compose file : 

```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/portainer/Files/AppData/Config/Nginx-Proxy/data:/data"
      - "/portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt/renewal:/etc/letsencrypt"
    environment:
      - "TZ=Europe/Rome" # set timezone, required
      - "ACME_EMAIL=xxxxx.xxx.xx"
      - "ACME_MUST_STAPLE=false"
      - "X_FRAME_OPTIONS=sameorigin"
      - "FULLCLEAN=true"
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npm/nginx/access.log, stream access logs to /opt/npm/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=2"
```


I'm running in on an lcx container in proxmox with 6 core and 8gb ram 

It's a dell server Xeon with ssd

**Comment by Zoey2936** [comment]
where are your upstreams running?

**Comment by Giuseppe-TD** [comment]
Websites and other upstreams are in the same network, on another container, but before the latest a updates the response time was good, I'm in fiber 1gbs down and 500 mbs up

**Comment by Zoey2936** [comment]
are they on the same host? / whats the lastency between npmplus and usptreams?

**Comment by Giuseppe-TD** [comment]
No they're are on another proxmox server on the same network, I can control them with the same login (proxmox) and the latency is about 0

**Comment by Zoey2936** [comment]
you can try the following if you want:
 - set NGINX_DISABLE_PROXY_BUFFERING to true
 - try to move npmplus from lxc to the host or into a kvm (container in container makes less sense if you understand)
 - temporary disable crowdsec and test again, note the security aspect
 - enable NGINX_QUIC_BPF (also give the container privileged permissions), note the security aspect

**Comment by Giuseppe-TD** [comment]
lcx is a vm lighter than a real vm (called it in proxmox, so it's not a container in a container), container is called in proxmox but it's a virtual machine.
anyway to disable crowdsec i just need to edit /opt/npmplus/crowdsec/crowdsec.conf and set crowdsec off?
then i try with disable buffering

**Reply by Zoey2936** [reply]
yes just change true to false in this file
but lxc is a container (lxc = Linux Containers), it is a diffrent type of container, but it is still a container

**Comment by Giuseppe-TD** [comment]
i tried.. the response time is waaaaay much faster ( also in the backend of the websites for managing and updating), i get an error in the logs regarding : 

2025/02/17 22:53:55 [alert] 6407#6407: failed to create BPF map (1: Operation not permitted)
2025/02/17 22:53:55 [emerg] 6407#6407: ngx_quic_bpf_module failed to initialize properly, ignored.please check limits and note that nginx state now can be inconsistent and restart may be required
2025/02/17 22:53:55 [alert] 8337#8337: sched_setaffinity() failed (22: Invalid argument)

maybe i'm not configured right the env?

**Reply by Zoey2936** [reply]
does the npmplus container has privilleged permissions? if yes, then both of them are lxc related since npmplus has not enough permissions, or better said the lxc container has not enough permissions. What settings made it faster?

**Comment by Giuseppe-TD** [comment]
```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - "/portainer/Files/AppData/Config/Nginx-Proxy/data:/data"
      - "/portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt/renewal:/etc/letsencrypt"
    environment:
      - "NGINX_DISABLE_PROXY_BUFFERING=true"
      - "NGINX_QUIC_BPF=true"
      - "TZ=Europe/Rome" # set timezone, required
      - "ACME_EMAIL=xxx@xxx.xx"
      - "ACME_MUST_STAPLE=false"
      - "X_FRAME_OPTIONS=sameorigin"
      - "FULLCLEAN=true"
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npm/nginx/access.log, stream access logs to /opt/npm/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=2"
```

this is my compose now
