### DISCUSSION TITLE
Crowdsec + Cloudflare Configuration Query

### DISCUSSION THREAD

**Discussion by OfficialMuffin** [ZoeyVid/NPMplus#1582] [Q&A] [answered]
I have cloudflare as my domain name provider and proxy. Crowdsec is only picking up the public IP of my home thats being HTTP probed. Nextcloud that is an external server to the NPM Plus proxy but is being reverse proxied by NPM is also being served the public IP of my home. Is this the intended outcome? Can NPM or crowdsec somehow get the real IP of the attacker that is probing my network?

**Comment by Zoey2936** [comment]
your compose.yaml?

**Reply by OfficialMuffin** [reply]
My compose.yaml:

```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
#    ipc: service:openappsec-agent # required when you want to use the openappsec attachment module
#    privileged: true # required if you set NGINX_QUIC_BPF to true
    volumes:
      - "./npmplus:/data"
#      - "/var/www:/var/www" # optional, if you want to use NPMplus directly as webserver for html/php
    environment:
      - "TZ=Europe/London" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - "PUID=1001" # set group id, needs to be a number greater or equal to 99, or equal to 0, default 0 (root)
      - "PGID=1001" # set user id, needs to be a number greater or equal to 99, or equal to 0, default 0 (root), requires PUID to be not 0
      - "DISABLE_IPV6=true" # fully disables listing on IPv6 and the IPv6 resolver of nginx, overrides IPV6_BINDING/NPM_IPV6_BINDING/GOA_IPV6_BINDING, default false
      - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npmplus/nginx/access.log, stream access logs to /opt/npmplus/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=7" # Set how often the access.log should be rotated until it is deleted, default 3


# This can be used with DISABLE_HTTP=true, to force HTTPS redirects for every host
  npmplus-caddy:
      container_name: npmplus-caddy
      image: docker.io/zoeyvid/npmplus:caddy
      restart: always
      network_mode: bridge
      ports:
        - "80:80"
      environment:
        - "TZ=Europe/London"

# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8081:8080"
    environment:
      - "TZ=Europe/London" # needs to be changed
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "./crowdsec/conf:/etc/crowdsec"
      - "./crowdsec/data:/var/lib/crowdsec/data"
      - "./npmplus/nginx:/opt/npmplus/nginx:ro"
      - "/run/user/1001/podman/podman.sock:/var/run/docker.sock:ro"


```
