### DISCUSSION TITLE
Error when browsing sites that are proxied

### DISCUSSION THREAD

**Discussion by OfficialMuffin** [ZoeyVid/NPMplus#1609] [Q&A] [answered]
Hi, I felt like IP's wern't getting blocked so I checked the logs for the NPMPlus container and these lines stood out. I guessed it was an issue connecting the bouncer to crowdsec LAPI so I went through the crowdsec setup instructions on this repo again. It didnt fix anything:

```
[npmplus]       | 2025/03/13 22:05:08 [error] 4794#4794: *5 connect() failed (111: Connection refused), client: [REDACTED IP], server: [REDACTED DOMAIN], request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/2.0", host: "[REDACTED DOMAIN]"
[npmplus]       | 2025/03/13 22:05:08 [error] 4794#4794: *5 [lua] crowdsec.lua:636: Allow(): [Crowdsec] bouncer error: request failed: connection refused, client: [REDACTED IP], server: [REDACTED DOMAIN], request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/2.0", host: "[REDACTED DOMAIN]"
```

**Comment by Zoey2936** [comment]
please post your npmplus.yaml your compose.yaml and your crowdsec.conf (and remove the secrets)

**Reply by OfficialMuffin** [reply]
compose.yaml:
```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
#    ipc: service:openappsec-agent # required when you want to use the openappsec attachment module
#    privileged: true # required if you set NGINX_QUIC_BPF to true
    volumes:
      - "./npmplus:/data"
#      - "/var/www:/var/www" # optional, if you want to use NPMplus directly as webserver for html/php
    environment:
      - "TZ=Europe/London" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - "PUID=1001" # set group id, needs to be a number greater or equal to 99, or equal to 0, default 0 (root)
      - "PGID=1001" # set user id, needs to be a number greater or equal to 99, or equal to 0, default 0 (root), requires PUID to be not 0
      - "DISABLE_IPV6=true" # fully disables listing on IPv6 and the IPv6 resolver of nginx, overrides IPV6_BINDING/NPM_IPV6_BINDING/GOA_IPV6_BINDING, default false
      - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npmplus/nginx/access.log, stream access logs to /opt/npmplus/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=7" # Set how often the access.log should be rotated until it is deleted, default 3


# This can be used with DISABLE_HTTP=true, to force HTTPS redirects for every host
  npmplus-caddy:
      container_name: npmplus-caddy
      image: docker.io/zoeyvid/npmplus:caddy
      restart: always
      network_mode: bridge
      ports:
        - "80:80"
      environment:
        - "TZ=Europe/London"

# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8081:8080"
    environment:
      - "TZ=Europe/London" # needs to be changed
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "./crowdsec/conf:/etc/crowdsec"
      - "./crowdsec/data:/var/lib/crowdsec/data"
      - "./npmplus/nginx:/opt/npmplus/nginx:ro"
      - "/run/user/1001/podman/podman.sock:/var/run/docker.sock:ro"

```

npmplus.yaml:
```
# Added from https://github.com/ZoeyVid/NPMplus
filenames:
  - /opt/npmplus/nginx/access.log
labels:
  type: npmplus
---
source: docker
container_name:
 - npmplus
labels:
  type: npmplus
---
source: docker
container_name:
 - npmplus
labels:
  type: modsecurity
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: appsec
source: appsec
labels:
  type: appsec
```

crowdsec.conf:
```
ENABLED=true
API_URL=http://127.0.0.1:8080
API_KEY=REDACTED
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://127.0.0.1:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true

```
