### DISCUSSION TITLE
Using NPMPlus with Host mode cant proxy hosts

### DISCUSSION THREAD

**Discussion by mr-ulusoy** [ZoeyVid/NPMplus#1612] [Q&A] [answered]
I have problem to proxy hosts when Im on Host mode. I tried diffrent hosts and to use http and https schems but none of them worked. I also tried diffrent browsers and in ingonito mode.  I use Cloudflare as DNS and proxy my domain, run this on Ubuntu AArch64 (ARM64) as hardware. I switch off proxy and that didnt help. Running same config on bridge mode works as expected.

my docker-compose file 
```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
        volumes:
      - "/home/ubuntu/docker/npmplus:/data"
       environment:
      - "TZ=Europe/London" 
      - "ACME_EMAIL=myemail" 
      - "NGINX_LOG_NOT_FOUND=true" # Allow logging of 404 errors, default false
      - "LOGROTATE=true" 
      - "LOGROTATIONS=7" 
      - "X_FRAME_OPTIONS=sameorigin" 
```

**Comment by Zoey2936** [comment]
can you reach your upstreams with curl from the host?

**Reply by mr-ulusoy** [reply]
Yes,  I can.

**Reply by Zoey2936** [reply]
and the same curl command within the container?

**Reply by mr-ulusoy** [reply]
Yes, from NPMplus and the host.

**Reply by Zoey2936** [reply]
does nginx logs something?

**Reply by mr-ulusoy** [reply]
There was nothing on the nginx logs, so I reinstalled all rebooted the host twice and now host mode is working now. 
But I have problem with crowdsec, I added manual ip to decision list but its not blocking traffic. I added my VPNs external ip, on nginx I can see the my ip(banned) accessing my website.

I edit npmplus.yaml and crowdsec.conf redeloyed but no luck. What should I troubleshoot?

```
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8080:8080"
    environment:
      - "TZ=Europe/London" # needs to be changed
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/home/ubuntu/docker/crow-npm/conf:/etc/crowdsec"
      - "/home/ubuntu/docker/crow-npm/data:/var/lib/crowdsec/data"
      - "/home/ubuntu/docker/npmplus/nginx:/opt/npmplus/nginx:ro"
```


----
Crowdsec.conf
```
ENABLED=enable
API_URL=http://localhost:8080
API_KEY=myAPIkey
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=cloudflare
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://localhost:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true
```
---

 npmplus.yaml
```
filenames:
  - /opt/npmplus/nginx/*.log
labels:
  type: npmplus
---
filenames:
  - /opt/npmplus/nginx/*.log
labels:
  type: modsecurity
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: appsec
source: appsec
labels:
  type: appsec
```
