### DISCUSSION TITLE
Trying to connect Crowdsec to a LAPI server on my network

### DISCUSSION THREAD

**Discussion by DJKatastrof** [ZoeyVid/NPMplus#1614] [Q&A] [answered]
Hi!

Trying to connect crowdsec to my lapi server, but it changes to local API every time. 

I'm trying to change server config in  /opt/crowdsec/conf/config.yaml  to enabled false.
But when ever I try to restart the container, it changes back to Enable: true.
Maybe I'm totally wrong, but some guidance would be appreciated 🙏🏼

```
  server:
    log_level: info
    listen_uri: 0.0.0.0:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    trusted_ips: # IP ranges, or IPs which can have admin API access
      - 127.0.0.1
      - ::1
    online_client: # Central API credentials (to push signals and receive bad IPs)
      credentials_path: /etc/crowdsec//online_api_credentials.yaml
    enable: false
```

Crowdsec.conf

```
ENABLED=true
API_URL=http://192.168.1.19:8080
API_KEY=redacted key
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://127.0.0.1:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true
```

Compose:
```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/opt/npmplus:/data"
    environment:
       - "TZ=Europe/Stockholm" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
       - "ACME_EMAIL=redacted" # email address which should be used for acme, currently optional, may be required in the future, so I recommend you to enter your email here, optional for letsencrypt, but required for zerossl and google public ca
       - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
       - "LOGROTATE=true" # Enables writing http access logs to /opt/npmplus/nginx/access.log, stream access logs to /opt/npmplus/nginx/stream.log and enables daily logrotation, default false

# This can be used with DISABLE_HTTP=true, to force HTTPS redirects for every host
  npmplus-caddy:
    container_name: npmplus-caddy
    image: docker.io/zoeyvid/npmplus:caddy
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
    environment:
      - "TZ=Europe/Stockholm"

# This can be used with GOA=true, to keep the geopip database updated, you need to change the envs to make it work
  geoipupdate:
    container_name: npmplus-geoipupdate
    image: docker.io/maxmindinc/geoipupdate:latest
    restart: always
    network_mode: bridge
    environment:
      - "TZ=Europe/Stockholm" # needs to be changed
      - "GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-City GeoLite2-ASN"
      - "GEOIPUPDATE_ACCOUNT_ID=Redacted" # needs to be changed
      - "GEOIPUPDATE_LICENSE_KEY=Redacted" # needs to be changed
      - "GEOIPUPDATE_FREQUENCY=24"
    volumes:
      - "/opt/npmplus/goaccess/geoip:/usr/share/GeoIP"

# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: host
    ports:
      - "7422:7422"
      - "8080:8080"
    environment:
      - "TZ=Europe/Stockholm" # needs to be changed
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/opt/crowdsec/conf:/etc/crowdsec"
      - "/opt/crowdsec/data:/var/lib/crowdsec/data"
      - "/opt/npmplus/nginx:/opt/npmplus/nginx:ro"
```

**Comment by Zoey2936** [comment, marked as answer]
see https://github.com/crowdsecurity/crowdsec/tree/master/docker#run-an-agent-connected-to-lapi

**Reply by DJKatastrof** [reply]
Oh that easy.. Can I ask another question?
I have connected to my lapi server now. But bans are not working, any ideas?

**Reply by Zoey2936** [reply]
did you updated the crowdsec.conf to use the the correct api server?

**Reply by DJKatastrof** [reply]
Yes, like this 
![image](https://github.com/user-attachments/assets/ffa1ee23-b827-40f3-b535-6760d114a6e5)

![image](https://github.com/user-attachments/assets/cad9c7f5-f25a-477e-b802-7607b2c7c147)

**Reply by Zoey2936** [reply]
how did you test if the bans work? / how did you triggered the ban?

**Reply by DJKatastrof** [reply]
Im using this, working on my authelia

`cscli decisions add --ip 192.168.1.136 --duration 1m --type ban`

**Reply by Zoey2936** [reply]
is this ip logged in the acces log?

**Reply by DJKatastrof** [reply]
yes :)
Seems like the bouncer on lapi server is not properly configured or crowdsec container is misconfigured

![image](https://github.com/user-attachments/assets/b4b2c273-c043-4f01-9460-89b3a6d87487)

**Reply by Zoey2936** [reply]
is something in the docker logs of npmplus?

**Reply by DJKatastrof** [reply]
I can see this, 
![image](https://github.com/user-attachments/assets/41c2debc-3032-42bb-9bc4-13279f190ebe)

**Reply by Zoey2936** [reply]
looks fine, does it work if you ban a non private ip?

**Reply by DJKatastrof** [reply]
Im still wondering whether my crowdsec containers IP should end up here? 


> Yes, like this 

![image](https://private-user-images.githubusercontent.com/64254359/423417338-ffa1ee23-b827-40f3-b535-6760d114a6e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIyMDgyODEsIm5iZiI6MTc0MjIwNzk4MSwicGF0aCI6Ii82NDI1NDM1OS80MjM0MTczMzgtZmZhMWVlMjMtYjgyNy00MGYzLWI1MzUtNjc2MGQxMTRhNmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE3VDEwMzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYTBjZDQ5Y2JhM2RiYjkyNjM5ZjA5NjZlNjgzY2RkM2EwNWExMjU0MTQ4ZDU0ZjQwNmM4NTBhOWY4ZjM3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nzD3tV21RtHKf_uOYgqnlt7GigBSljGhhsSp-pfSpX8)
>

**Reply by DJKatastrof** [reply]
And type should be npmplus bouncer

**Reply by Zoey2936** [reply]
can you maybe post your current compose file(s) and other configs?

**Comment by DJKatastrof** [comment]
Compose: 

```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/opt/npmplus:/data"
    environment:
      - "TZ=Europe/Stockholm" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - "ACME_EMAIL=redacted" # email address which should be used for acme, currently optional, may be required in the future, so I recommend you to enter your email here, optional for letsencrypt, but required for zerossl and google public ca
      - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npmplus/nginx/access.log, stream access logs to /opt/npmplus/nginx/stream.log and enables daily logrotation, default false
# This can be used with DISABLE_HTTP=true, to force HTTPS redirects for every host
  npmplus-caddy:
    container_name: npmplus-caddy
    image: docker.io/zoeyvid/npmplus:caddy
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
    environment:
      - "TZ=Europe/Stockholm"

# This can be used with GOA=true, to keep the geopip database updated, you need to change the envs to make it work
  geoipupdate:
    container_name: npmplus-geoipupdate
    image: docker.io/maxmindinc/geoipupdate:latest
    restart: always
    network_mode: bridge
    environment:
      - "TZ=Europe/Stockholm" # needs to be changed
      - "GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-City GeoLite2-ASN"
      - "GEOIPUPDATE_ACCOUNT_ID=redacted" # needs to be changed
      - "GEOIPUPDATE_LICENSE_KEY=redacted" # needs to be changed
      - "GEOIPUPDATE_FREQUENCY=24"
    volumes:
      - "/opt/npmplus/goaccess/geoip:/usr/share/GeoIP"

# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: host
    ports:
      - "7422:7422"
      - "8080:8080"
    environment:
      - "TZ=Europe/Stockholm" # needs to be changed
      - "COLLECTIONS=ZoeyVid/npmplus"
      - "DISABLE_LOCAL_API=true"
      - "LOCAL_API_URL=http://192.168.1.19:8080"
    volumes:
      - "/opt/crowdsec/conf:/etc/crowdsec"
      - "/opt/crowdsec/data:/var/lib/crowdsec/data"
      - "/opt/npmplus/nginx:/opt/npmplus/nginx:ro"

```


**/opt/npmplus/crowdsec.conf**
```
ENABLED=true
API_URL=http://192.168.1.19:8080
API_KEY=redacted
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://127.0.0.1:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true
```


**crowdsec config.yaml**
```
common:
  daemonize: false
  log_media: stdout
  log_level: info
  log_dir: /var/log/
config_paths:
  config_dir: /etc/crowdsec/
  data_dir: /var/lib/crowdsec/data/
  simulation_path: /etc/crowdsec/simulation.yaml
  hub_dir: /etc/crowdsec/hub/
  index_path: /etc/crowdsec/hub/.index.json
  notification_dir: /etc/crowdsec/notifications/
  plugin_dir: /usr/local/lib/crowdsec/plugins/
crowdsec_service:
  acquisition_path: /etc/crowdsec/acquis.yaml
  acquisition_dir: /etc/crowdsec/acquis.d
  parser_routines: 1
plugin_config:
  user: nobody
  group: nobody
cscli:
  output: human
db_config:
  log_level: info
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db
  flush:
    max_items: 5000
    max_age: 7d
  use_wal: false
api:
  client:
    insecure_skip_verify: false
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 0.0.0.0:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    trusted_ips: # IP ranges, or IPs which can have admin API access
      - 127.0.0.1
      - ::1
    online_client: # Central API credentials (to push signals and receive bad IPs)
      credentials_path: /etc/crowdsec//online_api_credentials.yaml
    enable: false
prometheus:
  enabled: true
  level: full
  listen_addr: 0.0.0.0
  listen_port: 6060
```

LAPI server
![image](https://github.com/user-attachments/assets/15da61f1-24d6-4c20-b09e-e014088e2fd4)
