### DISCUSSION TITLE
NPM LetsEncrypt E6 cert and NPMPlus LetsEncrypt E5 cert

### DISCUSSION THREAD

**Discussion by DJKatastrof** [ZoeyVid/NPMplus#1630] [Q&A] [answered]
Hey,

On NPM my HomeAssistant is working fine, but whenever I switch over to NPMPlus and the certificate from Certbot I get weird errors in my ingress windows.
If i switch back to my original NPM instance everything works fine

Is this something someone else have found? 

![image](https://github.com/user-attachments/assets/b7468836-c4b2-4900-a914-a6338ae0db5c)

**Comment by Zoey2936** [comment]
is something logged? NPMplus docker logs and browser logs?

**Reply by DJKatastrof** [reply]
No nothing unsual, that's the most strange part. The only thing I found is that NPM cert is E6 and NPMPlus cert is E5. I don't think that matters

**Reply by Zoey2936** [reply]
can you try this for the homeassistant proxy host? https://github.com/ZoeyVid/NPMplus/discussions/1127#discussioncomment-12374027

**Reply by DJKatastrof** [reply]
Did not work. But I disabled HSTS and ingress windows start working. 
Yesterday I disabled HSTS and got certificate errors on my home assistant app on my phone. Will try it again today.

**Reply by Zoey2936** [reply]
I think I have an idea, cat you try the develop tag?

**Reply by DJKatastrof** [reply]
Sure, like this?

image: docker.io/zoeyvid/npmplus:develop ?

**Reply by Zoey2936** [reply]
yes

**Reply by DJKatastrof** [reply]
im getting randoms bans all over my network 

2025/03/21 09:28:38 [error] 585#585: *127 [lua] crowdsec.lua:569: Allow(): AppSec check: connection refused, client: 192.168.1.224, server: ha.dj.local, request: "POST /auth/token HTTP/2.0", host: "ha.dj.local", referrer: "https://ha.dj.local/calendar"
2025/03/21 09:28:38 [alert] 585#585: *127 [lua] crowdsec.lua:636: Allow(): [Crowdsec] denied '192.168.1.224' with 'ban' (by appsec), client: 192.168.1.224, server: ha.dj.local, request: "POST /auth/token HTTP/2.0", host: "ha.dj.local", referrer: "https://ha.dj.local/calendar"

**Reply by Zoey2936** [reply]
is this a different issue? please post you compose.yaml crowdsec.conf and npmplus.yaml

**Reply by DJKatastrof** [reply]
I had to rollback from snapshot. everything got banned 😅

**Reply by DJKatastrof** [reply]
compose 

```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/opt/npmplus:/data"
    environment:
      - "TZ=Europe/Stockholm" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - "ACME_EMAIL=redacted" # email address which should be used for acme, currently optional, may be required in the future, so I recommend you to enter your email here, optional for letsencrypt, but required for zerossl and google public ca
      - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npmplus/nginx/access.log, stream access logs to /opt/npmplus/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=7" # Set how often the access.log should be rotated until it is deleted, default 3

# This can be us#ed with DISABLE_HTTP=true, to force HTTPS redirects for every host
  npmplus-caddy:
    container_name: npmplus-caddy
    image: docker.io/zoeyvid/npmplus:caddy
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
    environment:
      - "TZ=Europe/Stockholm"

# This can be used with GOA=true, to keep the geopip database updated, you need to change the envs to make it work
  geoipupdate:
    container_name: npmplus-geoipupdate
    image: docker.io/maxmindinc/geoipupdate:latest
    restart: always
    network_mode: bridge
    environment:
      - "TZ=Europe/Stockholm" # needs to be changed
      - "GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-City GeoLite2-ASN"
      - "GEOIPUPDATE_ACCOUNT_ID=redacted" # needs to be changed
      - "GEOIPUPDATE_LICENSE_KEY=redacted" # needs to be changed
      - "GEOIPUPDATE_FREQUENCY=24"
    volumes:
     - "/opt/npmplus/goaccess/geoip:/usr/share/GeoIP"

# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: host
    ports:
      - "7422:7422"
      - "8080:8080"
    environment:
      - "TZ=Europe/Stockholm" # needs to be changed
      - "COLLECTIONS=ZoeyVid/npmplus"
      - "DISABLE_LOCAL_API=true"
      - "LOCAL_API_URL=http://192.168.1.19:8080"
    volumes:
      - "/opt/crowdsec/conf:/etc/crowdsec"
      - "/opt/crowdsec/data:/var/lib/crowdsec/data"
      - "/opt/npmplus/nginx:/opt/npmplus/nginx:ro"
#      - "/opt/openappsec/logs:/opt/openappsec/logs:ro" # only uncomment if you also use the openappsec-agent container
```

Crowdsec.conf 

```
ENABLED=true
API_URL=http://192.168.1.19:8080
API_KEY=redacted
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://127.0.0.1:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true
```

npmplus.yaml

```
filenames:
  - /opt/npmplus/nginx/*.log
labels:
  type: npmplus
---
filenames:
  - /opt/npmplus/nginx/*.log
labels:
  type: modsecurity
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: appsec
source: appsec
labels:
  type: appsec
# if you use openappsec you can enable this
#---
#source: file
#filenames:
# - /opt/openappsec/logs/cp-nano-http-transaction-handler.log*
#labels:
#  type: openappsec
```
