### DISCUSSION TITLE
Migration from npm to npm+ – Issues with Proxy Resolution in Host Network Mode

### DISCUSSION THREAD

**Discussion by alex-1987** [ZoeyVid/NPMplus#1645] [Q&A] [answered]
Subject: Migration from npm to npm+ – Issues with Proxy Resolution in Host Network Mode

Hello everyone,

I recently migrated from the old npm setup to npm+ and wanted to share my configuration along with an issue I encountered regarding proxy hosts. In my previous setup, I had roughly 30 proxy configurations connected via the Docker proxy host without specifying ports. 
I wanan use Crowdsec thats why i wanna have Host mode:

For example, I used settings like:

    Domain Name: https://dashboard.example.com/

    Schema: http

    IP/Domain: proxyservice

    Port: 3000

After migrating, none of these proxy hosts seem to work. When using host network mode in npm+, I’m receiving error messages similar to:

`homepage could not be resolved (3: Host not found), client: <10.0.2.2>, server: dashboard.example.com, request: "GET / HTTP/2.0", host: "dashboard.example.net", referrer: "https://dashboard.example.com:....."`

For instance, running the following command inside the container:
```

docker exec -ti npmplus bash
curl http://homepage:3000
```

results in:

`curl: (6) Could not resolve host: http://homepage:3000`

Interestingly, if I comment out the network_mode: host line in the npm+ configuration and attach the container to the web network instead, the proxies work as expected.

Below is my YAML configuration with sensitive data redacted:
```

services:
  npmplus:
    container_name: npmplus
    image: docker.io/username/npmplus:latest  # or ghcr.io/username/npmplus:latest
    restart: always
    network_mode: host
    #    ipc: service:openappsec-agent # required when you want to use the openappsec attachment module
    #    privileged: true # required if you set NGINX_QUIC_BPF to true
    #    ports:
    #      - 80:80
    #      - 443:443
    #      - 81:81

    environment:
      - "TZ=Your/Timezone"  # Set to your preferred timezone, e.g., Europe/Berlin
      - "ACME_EMAIL=your-email@example.com"  # Email for acme, recommended for certificate providers
      - "DISABLE_IPV6=true"
      - "LOGROTATE=true"
      - "NGINX_LOG_NOT_FOUND=true"
    volumes:
      - /data/npmplus/data:/data
      - /data/npmplus/letsencrypt:/etc/letsencrypt
    # networks:
    #   - web

  mongo:
    image: mongo
    container_name: mongo-container
    labels:
      komodo.skip:  # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - komodo
    # ports:
    #   - 27017:27017
    volumes:
      - /data/komodo/db:/data/db
      - /data/komodo/db/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}

  core:
    image: ghcr.io/username/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo
    labels:
      komodo.skip:  # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - komodo
      - web
    # ports:
    #   - 9120:9120
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - repo-cache:/repo-cache
      - /data/komodo/core.config.toml:/config/config.toml

  periphery:
    image: ghcr.io/username/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-peri
    labels:
      komodo.skip:  # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - komodo
    env_file: .env
    environment:
      PERIPHERY_REPO_DIR: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/repos
      PERIPHERY_STACK_DIR: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/stacks
      PERIPHERY_SSL_KEY_FILE: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/ssl/key.pem
      PERIPHERY_SSL_CERT_FILE: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/ssl/cert.pem
    volumes:
      - /data/komodo/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      
volumes:
  repo-cache:

networks:
  web:
  komodo:
```

Questions & Discussion:

- Network Mode Impact: Has anyone else experienced DNS resolution issues with npm+ when using network_mode: host?
- Potential Workarounds: Are there any recommended configurations or workarounds to maintain proxy resolution without having to switch to the web network?
- Best Practices: What would be the best practice for setting up proxy hosts in this new environment?
- I appreciate any insights, workarounds, or recommendations from the community.

Thank you in advance for your help!

Best regards,
Alex
