### DISCUSSION TITLE
[SOLVED] Problem migrating from npm to npmplus - No certificates and no proxy hosts

### DISCUSSION THREAD

**Discussion by emailforos** [ZoeyVid/NPMplus#1682] [Q&A] [answered]
Hi.

I'm trying to migrate from npm to npm+ with no success.

My simple npm+ compose is:

```
services:
  npmplus:
    container_name: npmplus
    image: ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/opt/npmplus:/data"
#      - "/var/www:/var/www" # optional, if you want to use NPMplus directly as webserver for html/php
      - "/home/user/docker/npm/letsencrypt:/etc/letsencrypt" # Only needed for first time migration from original nginx-proxy-manager to this fork
    environment:
      - "TZ=${TZ}" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - "ACME_EMAIL=xxxxxxxxxxxx@gmail.com" # email address which should be used for acme, currently optional, may be required in the future, so I recommend you to enter your email here, optional for letsencrypt, but required for zerossl and google public ca

networks:
  dockernet:
    external: true
```
And my original npm compose is:

```
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      PUID: 1001
      PGID: 1001
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
        dockernet:
            ipv4_address: 172.20.0.30

networks:
  dockernet:
    external: true
```

My install logs are in: [https://pastebin.com/raw/Gr7TLUNn](https://pastebin.com/raw/Gr7TLUNn)

When following the guide in [https://github.com/ZoeyVid/NPMplus?tab=readme-ov-file#migration]( https://github.com/ZoeyVid/NPMplus?tab=readme-ov-file#migration) seems to do migration correct but when I enter into de webui admin there are no proxy hosts and no certificates there.

Anybody has an idea or suggestion of what I'm doing wrong? Is there any manually way of doing it instead of being the first deployment which is doing it?

Thanking in advance for your help.
