### DISCUSSION TITLE
[help with configuration] NPMPlus as web server for Roundcube mail with Authentik OAuth2 authentication

### DISCUSSION THREAD

**Discussion by alexsalex** [ZoeyVid/NPMplus#1757] [Q&A] [answered]
Deployed NPM Plus, create virtual host for Roundcube with PHP3 fpm (and a lot of modules).

Everything works except OAuth2. Site can't exchange the keys.

Found working config for Nginx, but NPM doesn't allow me to add it, host become disabled in NPM Plus.

here is the part of the config related to php-fpm:

```
        # PHP-FPM
        location ~ \.php$ {
 
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                try_files $fastcgi_script_name = 404;
                set $path_info $fastcgi_path_info;
 
                fastcgi_param PATH_INFO          $path_info;
                fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
                fastcgi_param QUERY_STRING       $query_string;
                fastcgi_param REQUEST_METHOD     $request_method;
                fastcgi_param CONTENT_TYPE       $content_type;
                fastcgi_param CONTENT_LENGTH     $content_length;
 
                fastcgi_param SCRIPT_NAME        $fastcgi_script_name;
                fastcgi_param REQUEST_URI        $request_uri;
                fastcgi_param DOCUMENT_URI       $document_uri;
                fastcgi_param DOCUMENT_ROOT      $document_root;
                fastcgi_param SERVER_PROTOCOL    $server_protocol;
                fastcgi_param REQUEST_SCHEME     $scheme;
                fastcgi_param HTTPS              $https if_not_empty;
 
                fastcgi_param GATEWAY_INTERFACE  CGI/1.1;
                fastcgi_param SERVER_SOFTWARE    nginx/$nginx_version;
 
                fastcgi_param REMOTE_ADDR        $remote_addr;
                fastcgi_param REMOTE_PORT        $remote_port;
                fastcgi_param SERVER_ADDR        $server_addr;
                fastcgi_param SERVER_PORT        $server_port;
                fastcgi_param SERVER_NAME        $server_name;
                fastcgi_param REDIRECT_STATUS    200;
 
 
                fastcgi_pass unix:/run/php/php8.3-fpm.sock;
                fastcgi_index index.php;
                fastcgi_buffers 8 16k;
                fastcgi_buffer_size 32k;
 
        }
```

How can I implement this config in to NPM plus web server?

Issue related only for `fastcgi_param` ...

**Comment by Zoey2936** [comment]
so does php fpm run inside the NPMplus container or outside? can you please also post your compoose.yaml and screenshots of your current configuration, please?

**Comment by alexsalex** [comment]
PHP runs in NPM Plus container.

<img width="524" alt="Screenshot 2025-05-01 at 1 42 27 PM" src="https://github.com/user-attachments/assets/e3fca1e4-9325-459c-8bb2-d83e9f6d284a" />

```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest
    restart: always
    env_file: stack.env
    privileged: true # required if you set NGINX_QUIC_BPF to true
    dns:
      - 1.1.1.1
    network_mode: host
    volumes:
      - "/opt/npmplus:/data"
      - "/var/www:/var/www" # optional, if you want to use NPMplus directly as webserver for html/php
```

Env:

```
TZ=America/Los_Angeles
ACME_EMAIL=test@test.com
FULLCLEAN=true
NGINX_QUIC_BPF=true
LOGROTATE=true
LOGROTATIONS=7
NPM_LISTEN_LOCALHOST=true
GOA_LISTEN_LOCALHOST=true
NGINX_LOAD_FANCYINDEX_MODULE=true
NGINX_LOAD_VHOST_TRAFFIC_STATUS_MODULE=true
PHP83=true
PHP83_APKS=php83-curl php83-common php83-openssl php83-mbstring php83-session php83-sqlite3 php83-pdo php83-pdo_sqlite php83-cli php83-dom php83-xml php83-intl php83-ctype php83-fileinfo php83-exif php83-iconv php83-ldap php83-gd php83-xmlwriter php83-zip
```
