### DISCUSSION TITLE
[error] 318#318: [lual crowdsec. lua:130: init(): APPSEC is enabled on 'crowdsec:7422'

### DISCUSSION THREAD

**Discussion by iDrzn** [ZoeyVid/NPMplus#1827] [Q&A] [answered]
Can someone help me I’ve been fighting for days

```
2025/05/18 23:06:20 [error] 318#318: [lual crowdsec.lua:73: init(): error loading captcha plugin: no recap
key provided, can't use recaptcha
2025/05/18 23:06:20 [error] 318#318: [lual crowdsec. lua:130: init(): APPSEC is enabled on 'crowdsec:7422'
2025/05/18 23:06:20 [alert] 318#318: [lua] crowdsec.conf:3):8: [Crowdsec] Initialisation done
```
```
2025/05/18 22:57:29 [error] 1055#1055: *78 [lua] live.lua:39: live_query(): failed to query LAPI http://crowdsec:8080/v1/decisions?ip=91.15.189.158: timeout, client: 91.15.189.158, server: *****.de, request: "GET /api/v3/calendar?start=2025-05-17&end=2025-05-18&includeSeries=True HTTP/2.0", host: "*****.de"
```
```yaml
services:
npmplus:
container_name: npmplus
image: zoeyvid/npmplus:latest
restart: always
networks:
vhome:
ipv4_address: 1.4.9.10
proxy:
privileged: true
volumes:
- "/volume2/docker/proxy/npmplus:/data"

environment:
- "TZ=Europe/Berlin"
- "ACME_EMAIL=***@gmail.com"
- "PUID=1002"
- "PGID=1002"
- "LOGROTATE=true"
- "INITIAL_ADMIN_EMAIL=*****@gmail.com"
- "INITIAL_ADMIN_PASSWORD=******"

crowdsec:
container_name: crowdsec
image: crowdsecurity/crowdsec:latest
restart: always
networks:
proxy:

ports:
- "7422:7422"
- "8080:8080"
environment:
- "TZ=Europe/Berlin"
- "COLLECTIONS=ZoeyVid/npmplus"
- "PUID=1002"
- "PGID=1002"
volumes:
- "/volume2/docker/proxy/crowdsec/conf:/etc/crowdsec"
- "/volume2/docker/proxy/crowdsec/data:/var/lib/crowdsec/data"
- "/volume2/docker/proxy/npmplus/nginx:/opt/npmplus/nginx:ro"
```
```yaml
filenames:
- /opt/npmplus/nginx/*.log
labels:
type: npmplus
---
filenames:
- /opt/npmplus/nginx/*.log
labels:
type: modsecurity
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: appsec
source: appsec
labels:
type: appsec
# if you use openappsec you can enable this
#---
#source: file
#filenames:
# - /opt/openappsec/logs/cp-nano-http-transaction-handler.log*
#labels:
# type: openappsec
---
source: file
filenames:
- /var/log/syslog
labels:
type: syslog
```
```
ENABLED=true
API_URL=http://crowdsec:8080
API_KEY=4Ini7+ewoI9uEakslLStwyYp8suxAOphHz+r5qZh0Im
CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://crowdsec:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true
```
