### DISCUSSION TITLE
Issues with Firefly and Beszel

### DISCUSSION THREAD

**Discussion by Akusho** [ZoeyVid/NPMplus#1841] [Q&A] [answered]
Hello,
I have recently transitioned from using Cloudflare tunnels with NPM + Crowdsec to the same config with NPM Plus.
I have one issue that is not present when using the regular NPM stack - I cannot edit transactions in Firefly III (accounting) and I cannot see graphs in Beszel (monitoring software). I can create transactions in Firefly, but cannot edit them. It seems like NPMPlus is somehow blocking access to the databases of these containers. I cannot pull data for graphing in Beszel and cannot pull data about transactions to edit them.

When I access both these containers through LAN address everything works fine.

If I bring down the NPMPlus stack and replace with NPM everything goes back to normal as well.
I have tried to enable/disable various proxy settings without success. Anyone has any ideas what I have misconfigured?

My docker composes for NPM Plus and NPM:
```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "91:91"
      - "443:443"
    volumes:
      - "./npm:/data"
      - "./www:/var/www"
    environment:
      - "TZ=ZXC"
      - "ACME_EMAIL=ZXC"
      - "ACME_SERVER=https://api.buypass.com/acme/directory"   
      - "ACME_MUST_STAPLE=false"
      - "ACME_OCSP_STAPLING=false"
      - "ACME_KEY_TYPE=rsa"
      - "NPM_PORT=81"
      - "GOA_PORT=91"
      - "GOAIWSP=48692"
      - "DB_MYSQL_HOST=mariadb"
      - "DB_MYSQL_PORT=3306"
      - "DB_MYSQL_USER=nginxadmin"
      - "DB_MYSQL_PASSWORD=ZXC"
      - "DB_MYSQL_NAME=nginxdb"
      - "LOGROTATE=true"
      - "LOGROTATIONS=7"
      - "GOA=true"
      - "GOACLA=--agent-list --real-os --double-decode --anonymize-ip --anonymize-level=2 --keep-last=7 --with-output-resolver --no-query-string"
    depends_on:
      - mariadb
      - tunnel
    networks:
      npm_plus_crowdsec:
        ipv4_address: 172.25.0.4

  mariadb:
    image: 'mariadb:10.11.5'
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=ZXC"
      - "MYSQL_DATABASE=nginxdb"
      - "MYSQL_USER=nginxadmin"
      - "MYSQL_PASSWORD=ZXC"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      npm_plus_crowdsec:
        ipv4_address: 172.25.0.5

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: unless-stopped
    ports:
      - "7422:7422"
      - "8080:8080"
    environment:
      - "TZ=ZXC"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "./npm/crowdsec/conf:/etc/crowdsec"
      - "./npm/crowdsec/data:/var/lib/crowdsec/data"
      - "./npm/nginx:/opt/npm/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      npm_plus_crowdsec:
        ipv4_address: 172.25.0.6
    
  tunnel:
    container_name: Cloudflare-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ./Cloudflared:/etc/cloudflared
      - ./Cloudflared/config.yml:/etc/cloudflared/config.yml
    environment:
      TUNNEL_TOKEN: 'ZXC'
    networks:
      npm_plus_crowdsec:
        ipv4_address: 172.25.0.8

  geoipupdate:
    container_name: npmplus-geoipupdate
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    environment:
      - "TZ=ZXC"
      - "GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-City GeoLite2-ASN"
      - "GEOIPUPDATE_ACCOUNT_ID=ZXC"
      - "GEOIPUPDATE_LICENSE_KEY=ZXC"
      - "GEOIPUPDATE_FREQUENCY=24"
    volumes:
      - "./npm/goaccess/geoip:/usr/share/GeoIP"
    networks:
      npm_plus_crowdsec:
        ipv4_address: 172.25.0.14

networks:
  npm_plus_crowdsec:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
 ```
```
services:
  nginx_proxy_manager:
    image: 'lepresidente/nginxproxymanager'
    container_name: npm-crowdsec
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      PGID: "1000"
      SSL_CERTS_PATH: "/etc/ssl/certs/GTS_Root_R1.pem"
      TZ: "ZXC"
      ADMIN_PANEL_LOG: "1"
      CROWDSEC_BOUNCER: "1"
      OPENRESTY_DEBUG: "0"
      DB_MYSQL_HOST: "172.25.0.5"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ZXC" #
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./NGINXPM:/data
      - ./NGINXPM/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
      - tunnel
    networks:
      crowdsec_proxy:
        ipv4_address: 172.25.0.4

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    container_name: npm_db
    environment:
      MYSQL_ROOT_PASSWORD: 'ZXC'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'ZXC'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./MariaDB/mysql:/var/lib/mysql
    networks:
      crowdsec_proxy:
        ipv4_address: 172.25.0.5

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    expose:
      - 8080
    environment:
      PGID: "1000"
    volumes:
      - ./CrowdSec/data:/var/lib/crowdsec/data
      - ./CrowdSec/config:/etc/crowdsec
      - /var/log/auth.log:/var/log/auth.log:ro
      - ./NGINXPM/logs:/var/log/nginx:ro
    restart: unless-stopped
    networks:
      crowdsec_proxy:
        ipv4_address: 172.25.0.6

  tunnel:
    container_name: Cloudflare-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ./Cloudflared:/etc/cloudflared
      - ./Cloudflared/config.yml:/etc/cloudflared/config.yml
    environment:
      TUNNEL_TOKEN: 'ZXC'
    networks:
      crowdsec_proxy:
        ipv4_address: 172.25.0.8

  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: GoAccess
    restart: unless-stopped
    environment:
      - TZ=ZXC
      - PUID=998
      - PGID=100   
    ports:
      - '7880:7880'
    volumes:
      - ./NGINXPM/logs:/opt/log:ro
    networks:     
      crowdsec_proxy:
        ipv4_address: 172.25.0.7

networks:
  crowdsec_proxy:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
```
