### DISCUSSION TITLE
NPMPlus Integration with Crowdsec Dashboard

### DISCUSSION THREAD

**Discussion by bransoned** [ZoeyVid/NPMplus#1913] [Q&A] [answered]
Wondering if anyone has gotten the Crowdsec dashboard to work with NPMPlus or not. Figured I would ask here before I started changing docker configs.

**Comment by Zoey2936** [comment]
Which crowdsec dashboard?

**Reply by bransoned** [reply]
There seem to be a few different ways, but this is what the crowdsec container recommends: https://github.com/crowdsecurity/example-docker-compose/tree/main/basic. With the docker compose file being here: https://github.com/crowdsecurity/example-docker-compose/blob/main/basic/docker-compose.yml.

Wasn't sure if changing the volumes from the NPMPlus defaults would have any effect on NPMPlus working correctly, so wanted to check and see.

**Reply by Zoey2936** [reply]
you can try to append this to your compose.yaml:
```yaml
  crowdsec-metabase:
    container_name: crowdsec-metabase
    build: https://github.com/crowdsecurity/example-docker-compose.git#main:/basic/crowdsec/dashboard # should work, but not sure
    restart: always
    network_mode: bridge
    ports:
      - "<ip-to-bind-to>:3000:3000" # change
    environment:
      - "TZ=Europe/Berlin" # change
      - "MB_DB_FILE=/data/metabase.db"
      - "MGID=1000"
    volumes:
      - "/opt/crowdsec/data:/metabase-data" # if you haven't changed the path from the NPMplus compose.yaml
```

**Reply by bransoned** [reply, marked as answer]
Yep that looks like the same conclusion I got to:
```
  crowdsec-dashboard:
     username: crowdsec@crowdsec.net
     password: !!Cr0wdS3c_M3t4b4s3??
    container_name: crowdsec-dashboard
    # we're using a custom Dockerfile so that metabase pops with pre-configured dashboards
    build: https://raw.githubusercontent.com/crowdsecurity/example-docker-compose/refs/heads/main/basic/crowdsec/dashboard/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      MB_DB_FILE: /data/metabase.db/
      MGID: 1000
    depends_on:
      - crowdsec
    volumes:
      - /path/to/crowdsec/data:/metabase-data # change this
```

For anyone reading this using an ARM processor, this should be a working docker image as well (with the same user and password as above):
```
  crowdsec-dashboard:
    image: apollof/crowdsec_metabase:latest
    container_name: crowdsec-dashboard
    restart: unless-stopped
    depends_on:
      - crowdsec
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /path/to/crowdsec/data:/metabase-data # change this
```
