### DISCUSSION TITLE
ocsp not working

### DISCUSSION THREAD

**Discussion by scorpanv** [ZoeyVid/NPMplus#386] [Q&A] [answered]
Hi!

Can be upgraded the nginx to the version >=1.3.7 to be able to use OCSP Stapling?
Also to upgrade the https://github.com/ZoeyVid/nginx-proxy-manager to use newer version of nginx?

Thanks!
Victor Scorpan

**Comment by Zoey2936** [comment, marked as answer]
the latest version includes nginx v1.25.2, also npm uses OCSP by default

**Reply by scorpanv** [reply]
Thanks for quick reply.

It is true that version v1.25.2 has OCSP enabled by default, but unfortunately that doesn't support OCSP Stapling.
Yesterday, 31.08.2023 I installed the latest version of the "https://github.com/ZoeyVid/nginx-proxy-manager" via compose which uses nginx by https://github.com/ZoeyVid/nginx-quic , where at moment when I checked was the version v1.25.2 .

So, the default installed version generate certificate via CertBot which has issues in Firefox
![image](https://github.com/ZoeyVid/nginx-quic/assets/143760225/d39514d6-e67d-4080-a56f-0b64a5fed555)

The certificate can checked via these online tools:
https://www.ssllabs.com/ssltest/analyze.html?d=example.com&hideResults=on
![image](https://github.com/ZoeyVid/nginx-quic/assets/143760225/a46361d3-883b-4c4c-b21f-5560c5f55d64)
or via https://www.digicert.com/help/
![image](https://github.com/ZoeyVid/nginx-quic/assets/143760225/a457446d-9478-47e5-ba52-d563dcc90410)

Related to the article: https://www.digicert.com/kb/ssl-support/nginx-enable-ocsp-stapling-on-server.htm

> Nginx supports OCSP stapling in 1.3.7+. 

Yes, the workaround can be to instruct the CertBot to generate certificates without ocsp sample requirement.

Regards,
Victor Scorpan

**Reply by Zoey2936** [reply]
https://www.ssllabs.com/ssltest/analyze.html?d=mx.zvcdn.de&s=89.58.41.236&latest for me ocsp works. Can you send me your npm docker logs?

**Reply by Zoey2936** [reply]
https://www.ssllabs.com/ssltest/analyze.html?d=redcrafter07.de&hideResults=on same on this site running the npm fork

**Reply by scorpanv** [reply]
Thank you for references about ssltest with your domains, which make me to recheck my network setup, docker environment and configurations files.

Even I got the similar result on ssltest of my domain compared with yours "edcrafter07.de" from 2nd example. But anyway I think that I found the way to reproduce the issue. So my steps:

1. restart npm
2. after service loaded and run, check the desired domain served by restarted npm into Firefox browser, let say: https://edcrafter07.de . Just one time operation, paste or write the address and one time try to open, without any reload or try again actions. Expected the error: Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING
2a. the https://www.ssllabs.com/ssltest/analyze.html?d=redcrafter07.de&hideResults=on  expected to show the notification "This server certificate supports OCSP must staple but OCSP response is not stapled. ", paired with notification "OCSP Must Staple | Supported, OCSP response not stapled".
3. Once the page is reloaded, then there are no more error appearing. And after the check of the ssltest, no more notification "This server certificate supports OCSP must staple but OCSP response is not stapled. " and no more notification about "OCSP response not stapled". Further more page loading in Firefox are without any error and all ssltest are ok related to the "OCSP Must Staple" check.
4. The error starts appears again once the npm restarted.

So, a bit about my environment: I use docker on qnap environment on hardware designed for home usage. The network settings are: the docker run directly on network adapter from host (like direct access to the physical adapter), ip address and the other networks setup (like dns) are given by dhcp from local server from local network. Access to the npm from Internet are done by portforwarding of ports 80 and 443.

The npm related logs are:
```
2023/09/03 01:11:38 [error] 18085#18085: *572 [client 192.x.x.1] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:BLOCKING_INBOUND_ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/nginx/conf/conf.d/include/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "176"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "0"] [ver "OWASP_CRS/4.0.0-rc1"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "192.x.x.22"] [uri "/paht/name.svg"] [unique_id "169369629860.373730"] [ref ""], client: 192.x.x.1, server: subdomain.domain.com, request: "GET /paht/name.svg?${URL_RANDOM_NUM;} HTTP/2.0", host: "subdomain.domain.com", referrer: "https://subdomain.domain.com/relpath?r=form&1692068899"
----------------------------------------------------------
Let's Encrypt certificates cleanup - 2023/09/03 01:15:21
----------------------------------------------------------
Keeping /data/tls/certbot/archive/npm-7/cert1.pem.
Keeping /data/tls/certbot/archive/npm-7/chain1.pem.
Keeping /data/tls/certbot/archive/npm-7/fullchain1.pem.
Keeping /data/tls/certbot/archive/npm-7/privkey1.pem.
4 file(s) kept.
0 file(s) deleted.
skipped '/data/etc/modsecurity/crs-setup.conf'
no NPM_CERT_ID set, using dummycerts for npm and default hosts.
Working on file: /data/nginx/custom/events.conf
Working on file: /data/nginx/custom/http.conf
Working on file: /data/nginx/custom/http_top.conf
Working on file: /data/nginx/custom/root.conf
Working on file: /data/nginx/custom/server_dead.conf
Working on file: /data/nginx/custom/server_proxy.conf
Working on file: /data/nginx/custom/server_redirect.conf
Working on file: /data/nginx/custom/server_stream.conf
Working on file: /data/nginx/custom/server_stream_tcp.conf
Working on file: /data/nginx/custom/server_stream_udp.conf
Working on file: /data/nginx/custom/stream.conf
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/ip_ranges.conf
Working on file: /data/nginx/proxy_host/1.conf
Working on file: /data/nginx/proxy_host/2.conf
Success.

-------------------------------------
 _   _ ____  __  __
| \ | |  _ \|  \/  |
|  \| | |_) | |\/| |
| |\  |  __/| |  | |
|_| \_|_|   |_|  |_|
-------------------------------------
Version:  2.10.4+f9971aa
Date:     Sun Sep  3 01:15:23 CEST 2023
User:     root
PUID:     0
User ID:  0
PGID:     0
Group ID: 0
-------------------------------------

nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "r3.o.lencr.org" in the certificate "/data/tls/certbot/live/npm-7/fullchain.pem"
[Global   ] › ℹ  info      Using Sqlite: /data/etc/npm/database.sqlite
[Migrate  ] › ℹ  info      Current database version: none
[IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[IP Ranges] › ✖  error     getaddrinfo EAI_AGAIN ip-ranges.amazonaws.com
[SSL      ] › ℹ  info      Certbot Renewal Timer initialized
[SSL      ] › ℹ  info      Renewing TLS certs close to expiry...
[IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[Global   ] › ℹ  info      Backend PID 829 listening on port 48693 ...
[Nginx    ] › ℹ  info      Starting Nginx in three seconds
[SSL      ] › ℹ  info      Renew Complete
2023/09/03 01:15:51 [warn] 884#884: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2023/09/03 01:15:51 [warn] 884#884: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2023/09/03 01:15:51 [warn] 884#884: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2023/09/03 01:15:51 [notice] 884#884: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/796/0)
```

Looks the errors which I have is related to the notification from log:
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "r3.o.lencr.org" in the certificate "/data/tls/certbot/live/npm-7/fullchain.pem"
and
[IP Ranges] › ✖  error     getaddrinfo EAI_AGAIN ip-ranges.amazonaws.com

I will be very grateful if I get any suggestions how to correct this case.

Regards,
Victor Scorpan

**Reply by Zoey2936** [reply]
it seems like your dns does not work, can you please run `docker exec nginx-proxy-manager cat /etc/resolv.conf`

**Reply by scorpanv** [reply]
```
/app # cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
/app # 
```

**Reply by Zoey2936** [reply]
I am I correct that you use docker on windows?

**Reply by Zoey2936** [reply]
anyway please try to add `dns: 1.1.1.1` as line to your compose file and try again (you can also use an other dns resolver)

**Reply by scorpanv** [reply]
> I am I correct that you use docker on windows?

No, I try to use the docker in qnap on firmware QTS 5.1.1.2491 with Container Station Version 3.0.4.533 (2023/07/19)

> anyway please try to add dns: 1.1.1.1 as line to your compose file and try again (you can also use an other dns resolver)

I tried to recompose with dns option dns: 1.1.1.1 , but looks at some steps, the qnap (the app) overwrite this options and the nameserver remains the same as on previous version with value 127.0.0.11.
- Then I tried to follow the steps from these instructions: https://stackoverflow.com/a/62988037 (adding /etc/docker/daemon.json with dns settings)
Also without any success, nameserver has the same value 127.0.0.11
- Then based on answers from https://github.com/pi-hole/docker-pi-hole/issues/455#issuecomment-572115129 I recomposed the file. with new line > - "./resolv.conf:/etc/resolv.conf:ro" under volumes.
Also without any success. Even with nameserver changed:
```
/app # cat /etc/resolv.conf
nameserver  1.1.1.1
options ndots:0
/app # ^C
```

I have the similar npm log
```
----------------------------------------------------------
Let's Encrypt certificates cleanup - 2023/09/03 23:13:31
----------------------------------------------------------
Keeping /data/tls/certbot/archive/npm-7/cert1.pem.
Keeping /data/tls/certbot/archive/npm-7/chain1.pem.
Keeping /data/tls/certbot/archive/npm-7/fullchain1.pem.
Keeping /data/tls/certbot/archive/npm-7/privkey1.pem.
4 file(s) kept.
0 file(s) deleted.
skipped '/data/etc/modsecurity/crs-setup.conf'
no NPM_CERT_ID set, using dummycerts for npm and default hosts.
Working on file: /data/nginx/custom/events.conf
Working on file: /data/nginx/custom/http.conf
Working on file: /data/nginx/custom/http_top.conf
Working on file: /data/nginx/custom/root.conf
Working on file: /data/nginx/custom/server_dead.conf
Working on file: /data/nginx/custom/server_proxy.conf
Working on file: /data/nginx/custom/server_redirect.conf
Working on file: /data/nginx/custom/server_stream.conf
Working on file: /data/nginx/custom/server_stream_tcp.conf
Working on file: /data/nginx/custom/server_stream_udp.conf
Working on file: /data/nginx/custom/stream.conf
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/ip_ranges.conf
Working on file: /data/nginx/proxy_host/1.conf
Working on file: /data/nginx/proxy_host/2.conf
Success.
chown: changing ownership of '/var/www/index.html': Read-only file system
chown: changing ownership of '/var/www': Read-only file system

-------------------------------------
 _   _ ____  __  __
| \ | |  _ \|  \/  |
|  \| | |_) | |\/| |
| |\  |  __/| |  | |
|_| \_|_|   |_|  |_|
-------------------------------------
Version:  2.10.4+c943ccd
Date:     Sun Sep  3 23:13:33 CEST 2023
User:     root
PUID:     0
User ID:  0
PGID:     0
Group ID: 0
-------------------------------------

nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "r3.o.lencr.org" in the certificate "/data/tls/certbot/live/npm-7/fullchain.pem"
[Global   ] › ℹ  info      Using Sqlite: /data/etc/npm/database.sqlite
[Migrate  ] › ℹ  info      Current database version: none
[IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[IP Ranges] › ✖  error     getaddrinfo EAI_AGAIN ip-ranges.amazonaws.com
[SSL      ] › ℹ  info      Certbot Renewal Timer initialized
[IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[Global   ] › ℹ  info      Backend PID 829 listening on port 48693 ...
[Nginx    ] › ℹ  info      Starting Nginx in three seconds
2023/09/03 23:13:53 [warn] 870#870: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2023/09/03 23:13:53 [warn] 870#870: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2023/09/03 23:13:53 [warn] 870#870: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2023/09/03 23:13:53 [warn] 870#870: "ssl_stapling" ignored, host not found in OCSP responder "r3.o.lencr.org" in the certificate "/data/tls/certbot/live/npm-7/fullchain.pem"
2023/09/03 23:13:53 [notice] 870#870: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/796/0)
```
The same issue in Firefox remains.

Also tried to npm throught UI to add into advanced the configuration line
```
resolver 8.8.4.4 8.8.8.8;
```

The error remains in Firefox and into NPM logs.

I request the update of the nginx engine to the version 1.3.7, because I found in many articles that reference this specification version as "must" for the "OCSP Must Stable", like this article https://bobcares.com/blog/enable-ocsp-stapling-on-nginx/

In some article (now I can found the reference), I read that in nginx was a bug related to the OCSP Stable.

The last used compose file:
```
version: "3"
services:
    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        image: zoeyvid/nginx-proxy-manager
        restart: always
        mac_address: 02:42:4D:6C:BE:43
        networks:
            - nginx-ext-network
        dns:
            - 1.1.1.1
        volumes:
        - "/share/usr/nginx-ext/conf:/data"
        - "/share/usr/nginx-ext/www:/var/www:ro" # optional, if you want to use it as webserver for html/php
        - "/share/usr/nginx-ext/resolv.conf:/etc/resolv.conf:ro" # optional, if you want to use it as webserver for html/php
#        - "/opt/npm-letsencrypt:/etc/letsencrypt" # Only needed for first time migration from original nginx-proxy-manager to this fork
        environment:
        - "TZ=Europe/Ljubljana" # set timezone, default UTC
#        - "PUID=1000" # set group id, default 0 (root)
#        - "PGID=1000" # set user id, default 0 (root)
#        - "NIBEP=48693" # internal port, always bound to 127.0.0.1, default 48693, you need to change it, if you want to run multiple npm instances in network mode host
#        - "NPM_PORT=81" # Port the NPM backend should be bound to, default 81, you need to change it, if you want to run multiple npm instances in network mode host
#        - "IPV4_BINDING=127.0.0.1" # IPv4 address to bind, defaults to all
#        - "NPM_IPV4_BINDING=127.0.0.1" # IPv4 address to bind for the NPM backend, defaults to all
#        - "IPV6_BINDING=[::1]" # IPv6 address to bind, defaults to all
#        - "NPM_IPV6_BINDING=[::1]" # IPv6 address to bind for the NPM backend, defaults to all
#        - "DISABLE_IPV6=true" # disable IPv6, incompatible with IPV6_BINDING, default false
#        - "NPM_DISABLE_IPV6=true" # disable IPv6 for the NPM backend, incompatible with NPM_IPV6_BINDING, default false
#        - "NPM_LISTEN_LOCALHOST=true" # Bind the NPM Dashboard on Port 81 only to localhost, incompatible with NPM_IPV4_BINDING/NPM_IPV6_BINDING/NPM_DISABLE_IPV6, default false
#        - "NPM_CERT_ID=1" # ID of cert, which should be used instead of dummycerts, default unset/dummycerts
#        - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
#        - "NGINX_LOG_NOT_FOUND=true" # Allow logging of 404 errors, default false
#        - "CLEAN=false" # Clean folders, default true
#        - "FULLCLEAN=true" # Clean unused config folders, default false
#        - "PHP81=true" # Activate PHP81, default false
#        - "PHP81_APKS=php81-curl php-81-curl" # Add php extensions, see aviable packages here: https://pkgs.alpinelinux.org/packages?branch=v3.17&repo=community&arch=x86_64&name=php81-*, default none
#        - "PHP82=true" # Activate PHP82, default false
#        - "PHP82_APKS=php82-curl php-82-curl" # Add php extensions, see aviable packages here: https://pkgs.alpinelinux.org/packages?branch=v3.17&repo=community&arch=x86_64&name=php82-*, default none
networks:
    nginx-ext-network:
        external: true
        name: qnet-dhcp-eth0-6d6da6
```

Regards,
Victor Scorpan
