### DISCUSSION TITLE
Recommended Docker Desktop for Windows Compose

### DISCUSSION THREAD

**Discussion by FlattusBlastus** [ZoeyVid/NPMplus#481] [Q&A] [answered]
Zoey, I am loving your NPMPlus build. Adding the declared volume makes the data stay inside docker and not in the container. 
The data ends up living here \\wsl.localhost\docker-desktop-data\data\docker\volumes\npmplus\_data.
The following compose behaves nicely for DDfW:
```yaml
version: "3.8"
volumes:
  npmplus:
    name: npmplus
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: always
    network_mode: bridge
    ports:
      - 80:80
      - 81:81 #Port for the Admin Panel
      - 443:443
    volumes:
      - npmplus:/data
    environment:
      - TZ=US/Pacific
      - DISABLE_HTTP=true
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
