### DISCUSSION TITLE
NPMPlus suddenly stopped working

### DISCUSSION THREAD

**Discussion by PedroBuffon** [ZoeyVid/NPMplus#791] [Q&A] [answered]
Running NPM on the latest version on docker, was running fine but started getting 2024/04/29 12:31:23 [warn] 1486#1486: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem" messages, then every host stopped working. I tried deleting this dummycert but after a restart it came back with the same problem. idk what else to try.
here is my docker compose file
```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - /docker/npm:/data
    environment:
      - TZ=America/Sao_Paulo # set timezone, required
#      - PUID=1000 # set group id, default 0 (root)
#      - PGID=1000 # set user id, default 0 (root)
```

and port 80 and 443 are oppened on my firewall. if i try going to the local ip i can log in on NPM web gui
