### DISCUSSION TITLE
Help for NPMPlus + GoAccess + Crowsdec + GeoIP

### DISCUSSION THREAD

**Discussion by viriatusX** [ZoeyVid/NPMplus#797] [Q&A] [answered]
Good evening,
I'm trying to integrate everything on my Synology NAS but I can't get it.

This is my Compose:

```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: always
    network_mode: host
    volumes:
      - "/volume1/docker/npmplus:/data"
    environment:
      - "TZ=Europe/Madrid" 
      - "LOGROTATE=true" 
      - "GOA=true" # Enables goaccess, overrides LOGROTATE, default false --- if you download the GeoLite2-Country.mmdb, GeoLite2-City.mmdb AND GeoLite2-ASN.mmdb file from MaxMind and place them in /opt/npm/etc/goaccess/geoip it will automatically enable GeoIP in goaccess after restarting NPMplus (no need to change GOACLA below), you may also use the compose.geoip.yaml

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8080:8080"
    environment:
      - "TZ=Europe/Madrid"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/volume1/docker/crowdsec/conf:/etc/crowdsec"
      - "/volume1/docker/crowdsec/data:/var/lib/crowdsec/data"
      - "/volume1/docker/crowdsec/nginx:/opt/npm/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
I already have Geo2IP running in another container from before. I don't know how to "join" it so that GeoAccess detects it.

The rest of the Compose I have everything ok?

Thanks for your work.
