### DISCUSSION TITLE
tls/ssl cert issue

### DISCUSSION THREAD

**Discussion by Giuseppe-TD** [ZoeyVid/NPMplus#989] [Q&A] [answered]
after switching from npm "standard" to npmplus i got some troubles renewing the certs or obtain new.
if i check network avaibility i get this error:

There is no server available at this domain. Please make sure your domain exists and points to the IP where your NPM instance is running and if necessary port 80 is forwarded in your router.

the port is open and working, if i try with the standard npm it works.. so this must be something i miss from npmplus
this is my compose file:

```yaml
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: always
    network_mode: host
    volumes:
      - "/portainer/Files/AppData/Config/Nginx-Proxy/data:/data"
#      - "/var/www:/var/www" # optional, if you want to use it as webserver for html/php
    environment:
      - TZ=Europe/Rome # set timezone, required
```

i deleted the volumes lines #      - "/portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt:/etc/letsencrypt" # Only needed for first time migration from original nginx-proxy-manager to this fork, after the first starts

now i can't renew/add new certificates 
this supposed to open port 80 and 443, or enable in npmplus
