### DISCUSSION TITLE
crowdsec integration on npm plus

### DISCUSSION THREAD

**Discussion by Giuseppe-TD** [ZoeyVid/NPMplus#991] [Q&A] [answered]
hi again :D 

i just inserted crowdsec in the npm plus config:

```yaml
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: always
    network_mode: host
    volumes:
      - "/portainer/Files/AppData/Config/Nginx-Proxy/data:/data"
#      - "/var/www:/var/www" # optional, if you want to use it as webserver for html/php
    environment:
      - TZ=Europe/Rome # set timezone, required
      
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8080:8080"
    environment:
      - "TZ=Europe/Rome"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/opt/crowdsec/conf:/etc/crowdsec"
      - "/opt/crowdsec/data:/var/lib/crowdsec/data"
      - "/portainer/Files/AppData/Config/Nginx-Proxy:/opt/npm/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"`
```

this is the configuration, is ok? 
it's normal that i cant access crowdsec config by ip:8080 o 7422?
crowdsec blocks unautirozed access right? ( if try to access with multiple login fails?)
