### ISSUE TITLE
Container Health says unhealthy but its working fine!?

### ISSUE THREAD

**Issue by maieredv-manuel** [ZoeyVid/NPMplus#1014]
Hello,

at first i want to say thank you for your nice work :-)
Ive used "classic" NPM until some weeks ago, ive "upgraded" my Stack, but now i decided to reinstall all directly with NPMPlus.

But now i have a strange problem: the container runs fine, but in Portainer it says that its unhealthy - but i dont know why :-/

Kind regards
Manuel

**Comment by Zoey2936** [comment]
can you send me your compose.yaml?

**Comment by maieredv-manuel** [comment]
Sure :-)

```
services:
  npmplus:
    container_name: 01_NPMPlus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/docker-data/NPMPlus/opt/npm:/data"
      - "/docker-data/NPMPlus/var/www:/var/www"
    environment:
      - "PUID=0"
      - "PGID=0"
      - "TZ=Europe/Berlin"
      - "NPM_PORT=82"
      - "DISABLE_IPV6=true"
      - "NPM_DISABLE_IPV6=true"
      - "NPM_IPV4_BINDING=10.20.10.101"
      - "DEFAULT_CERT_ID=1"

```
