### ISSUE TITLE
Missing files/folders in docker container

### ISSUE THREAD

**Issue by Staubgeborener** [ZoeyVid/NPMplus#1173]
First of all this is my docker compose file:

```

services:
  npmplus:
    container_name: nginx_proxy_manager
    image: 'zoeyvid/npmplus'
    restart: unless-stopped
    #ports:
    #  - '80:80'
    #  - '81:81'
    #  - '443:443'
    volumes:
      - ./opt/npm:/data
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - NPM_PORT=81

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8080:8080"
    environment:
      - "TZ=Europe/Berlin"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - ./opt/crowdsec/conf:/etc/crowdsec
      - ./opt/crowdsec/data:/var/lib/crowdsec/data
      - ./opt/npm/nginx:/opt/npm/nginx:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
So i mounted the crowdsec folders directly inside the folder where my docker compose file is located (see`./opt` instead `/opt/`) which is on purpose. 

In the [guide](https://github.com/ZoeyVid/NPMplus?tab=readme-ov-file#crowdsec) is a section where stuff like

> 2. open `/opt/crowdsec/conf/acquis.d/npmplus.yaml` and fill it with:
> [...]
> 5. open `/opt/npm/etc/crowdsec/crowdsec.conf`

But looking into `./opt/crowdsec/conf/acquis.d/` there is no `npmplus.yaml`. Also there is in `/opt/npm/` there is no `/etc/` folder.
