### ISSUE TITLE
sched_setaffinity alerts

### ISSUE THREAD

**Issue by blunweon** [ZoeyVid/NPMplus#1492]
Hi there, been getting these alerts in the logs of Docker but otherwise the app works perfectly fine. Just wondering what they could mean?

![image](https://github.com/user-attachments/assets/e5a12943-0477-4a33-b2da-cd6824100c62)

**Comment by Zoey2936** [comment]
what cpu do you use? did you limit the cpu in docker? Thanks! Your compose file would be useful!

**Comment by blunweon** [comment]
I'm using a E5-2680v4. The Docker is running in a Proxmox LXC. I don't remember setting any affinity.

This is my compose.yaml file:
```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/npmplus:/data
      - /opt/npmplus:/tmp
    environment:
      - TZ=###myTZ
      - LOGROTATE=true
      - LOGROTATIONS=7
      - ACME_EMAIL=###mymail
      - ACME_SERVER=https://acme.zerossl.com/v2/DV90
      - ACME_EAB_KID=###mykey
      - ACME_EAB_HMAC_KEY=###mykey
      - ACME_MUST_STAPLE=false
      - ACME_OSCP_STAPLING=true
      - DEFAULT_CERT_ID=2
      #- REGENERATE_ALL=true #force regeneration of hosts files
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:dev
    restart: unless-stopped
    network_mode: host
    ports:
      - 7422:7422
      - 8080:8080
    environment:
      - TZ=###myTZ
      - COLLECTIONS=ZoeyVid/npmplus
    volumes:
      - /opt/crowdsec/conf:/etc/crowdsec
      - /opt/crowdsec/data:/var/lib/crowdsec/data
      - /opt/npmplus/nginx:/opt/npm/nginx:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks: {}
```
