### ISSUE TITLE
Help on websites

### ISSUE THREAD

**Issue by Giuseppe-TD** [ZoeyVid/NPMplus#1534]
I have several websites/proxy hosts (50) and I have some of them joomla websites for my clients, I'm starting a slowliness on the server response time, 800~ when on page speed should be less than 600, I started to notice it few updates ago, so I'm looking for a solution, should I maybe disable proxy buffering ? Or maybe add some variables to improve the performance ? 

This happen from 2/3 months ago before the response time was good

I'm using crowdsec .. this can be a problem?

**Comment by Zoey2936** [comment]
can you maybe tell more about your setup? hardware setup and network setup

**Comment by Giuseppe-TD** [comment]
This is my compose file : 

```
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/portainer/Files/AppData/Config/Nginx-Proxy/data:/data"
      - "/portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt/renewal:/etc/letsencrypt"
    environment:
      - "TZ=Europe/Rome" # set timezone, required
      - "ACME_EMAIL=xxxxx.xxx.xx"
      - "ACME_MUST_STAPLE=false"
      - "X_FRAME_OPTIONS=sameorigin"
      - "FULLCLEAN=true"
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npm/nginx/access.log, stream access logs to /opt/npm/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=2"
```


I'm running in on an lcx container in proxmox with 6 core and 8gb ram 

It's a dell server Xeon with ssd
