### ISSUE TITLE
Troubles with ip blocking

### ISSUE THREAD

**Issue by kitsune0n** [ZoeyVid/NPMplus#1561]
When trying manualy block ip, that's don't work
```
2834fe11e753:/# cscli decisions add --ip XXX.XXX.XXX.XXX --duration 10m --reason "manual test ban"
INFO Decision successfully added
2834fe11e753:/# cscli decisions list
╭───────┬────────┬───────────────────┬─────────────────┬────────┬─────────┬────┬────────┬────────────┬──────────╮
│   ID  │ Source │    Scope:Value    │      Reason     │ Action │ Country │ AS │ Events │ expiration │ Alert ID │
├───────┼────────┼───────────────────┼─────────────────┼────────┼─────────┼────┼────────┼────────────┼──────────┤
│ 15001 │ cscli  │ Ip:XXX.XXX.XXX.XX │ manual test ban │ ban    │         │    │ 1      │ 8m33s      │ 2        │
```

my compose.yaml
```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
#    ipc: service:openappsec-agent # required when you want to use the openappsec attachment module
#    privileged: true # required if you set NGINX_QUIC_BPF to true
    volumes:
      - "/data/npmplus:/data"
#      - "/var/www:/var/www" # optional, if you want to use NPMplus directly as webserver for html/php
#      - "/data/npmplus/letsencrypt:/etc/letsencrypt" # Only needed for first time migration from original nginx-proxy-manager to this fork
    environment:
      - "TZ=Europe/Kiev" # set timezone, required, set it to one of the values from the "TZ identifier" https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - "ACME_EMAIL=MYEMAIL@gmail.com" # email address which should be used for acme, currently optional, may be required in the future, so I recommend you to enter your email here, optional for letsencrypt, but required for zerossl and google public ca
      - "LOGROTATE=true" # Enables writing http access logs to /opt/npmplus/nginx/access.log, stream access logs to /opt/npmplus/nginx/stream.log and enables daily logrotation, default false
      - "LOGROTATIONS=7" # Set how often the access.log should be rotated until it is deleted, default 3
# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8182:8080"
    environment:
      - "TZ=Europe/Kiev"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/data/crowdsec/conf:/etc/crowdsec"
      - "/data/crowdsec/data:/var/lib/crowdsec/data"
      - "/data/npmplus/nginx:/opt/npmplus/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

my npmplus.yaml
kitsune@node0:/data/crowdsec/conf/acquis.d$ cat npmplus.yaml
```
filenames:
  - /opt/npmplus/nginx/access.log
labels:
  type: npmplus
---
source: docker
container_name:
 - npmplus
labels:
  type: npmplus
---
source: docker
container_name:
 - npmplus
labels:
  type: modsecurity
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: appsec
source: appsec
labels:
  type: appsec
```

my crowsec.conf
```
kitsune@node0:/data/npmplus/crowdsec$ cat crowdsec.conf
ENABLED=true
API_URL=http://127.0.0.1:8182

API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX MY API KEY GENERATED BYd ocker exec crowdsec cscli bouncers add npmplus -o raw

CACHE_EXPIRATION=1
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=2500
UPDATE_FREQUENCY=10
# By default internal requests are ignored, such as any path affected by rewrite rule.
# set ENABLE_INTERNAL=true to allow checking on these internal requests.
ENABLE_INTERNAL=false
# live or stream
MODE=live
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
#valid providers are recaptcha, hcaptcha, turnstile
CAPTCHA_PROVIDER=
# Captcha Secret Key
SECRET_KEY=
# Captcha Site key
SITE_KEY=
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
CAPTCHA_EXPIRATION=3600

APPSEC_URL=http://127.0.0.1:7422
APPSEC_FAILURE_ACTION=deny
APPSEC_CONNECT_TIMEOUT=1000
APPSEC_SEND_TIMEOUT=30000
APPSEC_PROCESS_TIMEOUT=10000
ALWAYS_SEND_TO_APPSEC=false
SSL_VERIFY=true
```

**Comment by Zoey2936** [comment]
and the compose yaml of crowdsec?

**Comment by kitsune0n** [comment]
```
# This can be used to enable crowdsec, see README for a guide
  crowdsec:
    container_name: crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    network_mode: bridge
    ports:
      - "127.0.0.1:7422:7422"
      - "127.0.0.1:8182:8080"
    environment:
      - "TZ=Europe/Kiev"
      - "COLLECTIONS=ZoeyVid/npmplus"
    volumes:
      - "/data/crowdsec/conf:/etc/crowdsec"
      - "/data/crowdsec/data:/var/lib/crowdsec/data"
      - "/data/npmplus/nginx:/opt/npmplus/nginx:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
