### ISSUE TITLE
nginx: [error] invalid PID number "" in "/usr/local/nginx/logs/nginx.pid"

### ISSUE THREAD

**Issue by nobee49** [ZoeyVid/NPMplus#1572]
I have setup the npmplus on dockge using this docker compose:
```
services:
  nginx-proxy-manager-plus:
    image: ghcr.io/zoeyvid/npmplus:latest
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 91:91
    volumes:
      - data:/data
    environment:
      - TZ=Europe/Berlin
      - ACME_EMAIL=
      - ACME_KEY_TYPE=ecdsa
      - ACME_SERVER_TLS_VERIFY=true
      - NGINX_LOAD_OPENAPPSEC_ATTACHMENT_MODULE=false
      - NGINX_LOAD_OPENTELEMETRY_MODULE=false
      - PUID=0
      - PGID=0
      - NIBEP=48681
      - GOAIWSP=48691
      - NPM_PORT=81
      - GOA_PORT=91
      - DISABLE_IPV6=false
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - HTTP3_ALT_SVC_PORT=443
      - DISABLE_HTTP=false
      - LISTEN_PROXY_PROTOCOL=false
      - DISABLE_H3_QUIC=false
      - NGINX_QUIC_BPF=true
      - NGINX_LOG_NOT_FOUND=false
      - NGINX_404_REDIRECT=false
      - NGINX_HSTS_SUBDMAINS=true
      - X_FRAME_OPTIONS=deny
      - NGINX_DISABLE_PROXY_BUFFERING=false
      - NGINX_WORKER_PROCESSES=auto
      - DISABLE_NGINX_BEAUTIFIER=false
      - FULLCLEAN=false
      - SKIP_IP_RANGES=false
      - LOGROTATE=true
      - LOGROTATIONS=3
      - CRT=24
      - IPRT=1
      - GOA=true
      - GOACLA=--agent-list --real-os --double-decode --anonymize-ip
        --anonymize-level=2 --keep-last=7 --with-output-resolver
        --no-query-string
      - INITIAL_DEFAULT_PAGE=404
    depends_on:
      crowdsec:
        condition: service_started
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: always
    ports:
      - 7422:7422
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
      - COLLECTIONS=ZoeyVid/npmplus
    volumes:
      - crowdsec-conf:/etc/crowdsec
      - crowdsec-data:/var/lib/crowdsec/data
      - /var/lib/docker/volumes/nginx-proxy-manager-plus_data/_data/nginx:/opt/npmplus/nginx:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  data:
    driver: local
  crowdsec-conf:
    driver: local
  crowdsec-data:
    driver: local
networks: {}
```

When I normally start it, everything works but when I restart my comupter to simulate a power loss or something like that it is not able to start again:

```
nginx: [error] invalid PID number "" in "/usr/local/nginx/logs/nginx.pid"
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |   
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |       at genericNodeError (node:internal/errors:983:15)
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |       at wrappedFn (node:internal/errors:537:14)
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |       at ChildProcess.exithandler (node:child_process:414:12)
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |       at ChildProcess.emit (node:events:524:28)
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |       at maybeClose (node:internal/child_process:1101:16)
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |       at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |     code: 1,
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |     killed: false,
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |     signal: null,
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |     cmd: 'nginx -s reload'
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |   },
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  |   public: false
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  | }
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  | 
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1  | Node.js v22.13.1
nginx-proxy-manager-plus-nginx-proxy-manager-plus-1 exited with code 1
```

I would be thankful for your help
