### ISSUE TITLE
NPMplus Container Fails to Start: requests.exceptions.SSLError

### ISSUE THREAD

**Issue by h0mesmart** [ZoeyVid/NPMplus#1629]
Hello there,

I'm encountering an issue while attempting to start an freshly installed NPMplus container using the following Compose.

```yaml
services:
  npmplus:
    image: ghcr.io/zoeyvid/npmplus:latest
    container_name: npmplus
    volumes:
      - "/usr/local/apps/npmplus:/data"
    environment:
      - "TZ=Europe/Berlin"
      - "ACME_EMAIL=--REDACTED--"
      - "ACME_SERVER=https://ca.homelab.lan/acme/acme/directory"
      - "ACME_KEY_TYPE=rsa"
      - "ACME_SERVER_TLS_VERIFY=false"
      - "CUSTOM_OCSP_STAPLING=true"
      - "PUID=1000" 
      - "PGID=1000"
      - "LOGROTATE=true"
      - "INITIAL_ADMIN_EMAIL=--REDACTED--"
      - "INITIAL_ADMIN_PASSWORD=--REDACTED--"
    restart: unless-stopped
    network_mode: host
```
 Despite explicitly configuring the container to not verify TLS for the ACME server, I'm still receiving an error. Here are the details:

```sh
npmplus  | 
npmplus  | -------------------------------------
npmplus  |  _ _  ___  __ __       _
npmplus  | | \ || . \|  \  \ ___ | | _ _  ___
npmplus  | |   ||  _/|     || . \| || | |[_-[
npmplus  | |_\_||_|  |_|_|_||  _/|_| \__|/__/
npmplus  |                  |_|
npmplus  | -------------------------------------
npmplus  | Version:  2.12.3+f53f2b4
npmplus  | Date:     Thu Mar 20 20:41:25 CET 2025
npmplus  | -------------------------------------
npmplus  | 
npmplus  | At least one env or the template version changed, all hosts will be regenerated.
npmplus  | no DEFAULT_CERT_ID set, using dummycerts.
npmplus  | usermod: no changes
npmplus  | 
npmplus  | -------------------------------------
npmplus  | User:     npm
npmplus  | PUID:     1000
npmplus  | User ID:  1000
npmplus  | PGID:     1000
npmplus  | Group ID: 1000
npmplus  | -------------------------------------
npmplus  | 
npmplus  | Saving debug log to /tmp/certbot-log/letsencrypt.log
npmplus  | An unexpected error occurred:
npmplus  | requests.exceptions.SSLError: HTTPSConnectionPool(host='ca.homelab.lan', port=443): Max retries exceeded with url: /acme/acme/directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))
npmplus  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log/letsencrypt.log or re-run Certbot with -v for more details.
```

I've explicitly set `ACME_SERVER_TLS_VERIFY=false`, which I believed would disable TLS verification for the ACME server. However, the container still fails to start due to the error above.

 Any assistance would be greatly appreciated. 

Thank you!
