### ISSUE TITLE
 [bug] Abnormally high memory usage when using coreruleset

### ISSUE THREAD

**Issue by cy1der** [ZoeyVid/NPMplus#1635]
I recently migrated all my 22 proxy hosts from regular NPM to NPMPlus, and I noticed that NPMPlus is consuming a concerning amount of memory, and it only increases over time.

```bash
~ sudo docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}" | (read header && echo "$header" && sort -h -k2)
NAME                            MEM USAGE / LIMIT
npmplus-geoipupdate             1.98MiB / 15.51GiB
...
crowdsec                        215.2MiB / 15.51GiB
...
npmplus                         2.472GiB / 15.51GiB
```

I checked the container's memory usage in the morning today and it was sitting at 1.5GB memory usage (which is already rather high, unless that's expected). I checked it the same day at night and it was sitting at 2.4GB, I checked out the processes inside the container and noticed that the nginx processes are using a lot of memory each.

```bash
~ sudo docker exec -it npmplus bash
dambi:/app# ps -o comm,rss | tail -n +2 | sort -k2 -rn
goaccess         3876
bash             2308
tail              868
nginx            785m
nginx            785m
nginx            784m
nginx            784m
nginx            784m
nginx            778m
sort              776
sh                772
nginx            771m
sleep             132
node              59m
sh                  8
sh                  8
ps                  4
tini                0
dambi:/app#
```

Is this normal? Or is there a memory leak happening somewhere?

**Comment by Zoey2936** [comment]
Do you use modsec/coreruleset? Or crowdsec? Or openappsec?

**Comment by Zoey2936** [comment]
For me it looks like this, I use crowdsec (no modsec/corerulesset and no openappsec):
```
arm:/app# ps -o comm,rss | tail -n +2 | sort -k2 -rn
nginx            5696
bash             2268
bash             2252
tail             1488
sort             1032
sh                528
sleep             280
node              45m
goaccess          25m
nginx             23m
nginx             19m
nginx             18m
nginx             18m
nginx             18m
nginx             17m
ps                  4
tini                0
sh                  0
sh                  0
```

**Comment by cy1der** [comment]
> Do you use modsec/coreruleset? Or crowdsec? Or openappsec?

I use modsec/crs and crowdsec, no openappsec

**Comment by Zoey2936** [comment]
can you temporary disable modsec for all hosts?

**Comment by cy1der** [comment]
After disabling modsec on the hosts and restarting the container, the memory usage has gone down to 125MB

**Comment by Zoey2936** [comment]
how many host do you have?

**Comment by cy1der** [comment]
22 proxy hosts. Also, I’m noticing that as I make more and more requests to the server, memory usage is still climbing, already doubled as we talk.

**Comment by Zoey2936** [comment]
so 250 per process or in total?

**Comment by cy1der** [comment]
Total

**Comment by Zoey2936** [comment]
can you post your compose.ymal please?

**Comment by cy1der** [comment]
```yaml

services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - data:/data
    environment:
      TZ: America/Toronto
      ACME_EMAIL: ...
      DEFAULT_CERT_ID: 1
      NGINX_QUIC_BPF: true
      NGINX_LOG_NOT_FOUND: true
      NGINX_DISABLE_PROXY_BUFFERING: true
      LOGROTATE: true
      GOA: true
      NGINX_LOAD_FANCYINDEX_MODULE: true
      NGINX_LOAD_GEOIP2_MODULE: true
      NGINX_LOAD_VHOST_TRAFFIC_STATUS_MODULE: true

  geoipupdate:
    container_name: npmplus-geoipupdate
    image: docker.io/maxmindinc/geoipupdate:latest
    restart: always
    network_mode: bridge
    environment:
      TZ: America/Toronto
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-City GeoLite2-ASN
      GEOIPUPDATE_ACCOUNT_ID: ...
      GEOIPUPDATE_LICENSE_KEY: ...
      GEOIPUPDATE_FREQUENCY: 24
    volumes:
      - type: volume
        source: data
        target: /usr/share/GeoIP
        volume:
          subpath: goaccess/geoip

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    depends_on:
      - npmplus
    ports:
      - 7422:7422
      - 8081:8080
    networks:
      - ntfy
    environment:
      TZ: America/Toronto
      COLLECTIONS: ZoeyVid/npmplus
    volumes:
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_config:/etc/crowdsec
      - type: volume
        source: data
        target: /npm_data/nginx
        read_only: true
        volume:
          subpath: nginx
    configs:
      - source: crowdsec_acquis
        target: /etc/crowdsec/acquis.yaml
      - source: crowdsec_ntfy
        target: /etc/crowdsec/notifications/ntfy.yaml

  crowdsec-firewall-bouncer:
    ...

configs:
  crowdsec_acquis:
    ...
  crowdsec_firewall_bouncer_config:
    ...
  crowdsec_ntfy:
    ...
      
volumes:
  data:
  crowdsec_data:
  crowdsec_config:
  geoip:

networks:
  ntfy:
    external: true
```
