### ISSUE TITLE
[bug] GoAccess --exclude-ip is ignored and database fails to persist

### ISSUE THREAD

**Issue by youngchaurachacha** [ZoeyVid/NPMplus#1936]
1. Bug Description
I am experiencing two issues with the integrated GoAccess feature in npmplus:
* IP Exclusion Not Working: Any IP addresses I try to exclude using the --exclude-ip argument within the GOACLA environment variable are not being filtered. They still appear in the real-time GoAccess dashboard.
* Database Not Persisting: The GoAccess database is not being saved. All statistics are lost whenever the container is restarted, despite the --persist and --db-path arguments being present in the launch command.
https://github.com/ZoeyVid/NPMplus/blob/4960a740f64eeff988f4d3e6d23b9fe0d0dfdf59/rootfs/usr/local/bin/launch.sh#L87

2. My docker-compose.yml
Here is the relevant service configuration:

```
services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "/volume1/docker/npmplus/data:/data"
    environment:
      - "GOA=true"
      - "GOACLA=--agent-list --real-os --double-decode --keep-last=30 --with-output-resolver --no-query-string --exclude-ip 127.0.0.1 --exclude-ip 10.0.0.0/8 --exclude-ip 172.16.0.0/12 --exclude-ip 192.168.0.0/16"
      # Other environment variables...
```

3. Steps to Reproduce
Deploy the container using the docker-compose.yml above.
Access a web service through NPM from a client with a private IP address (e.g., 192.168.50.1).
Open the GoAccess dashboard.
Observe that the private IP (192.168.50.1) is listed in the "Visitor Hostnames and IPs" panel.
Restart the container by running docker-compose down and docker-compose up -d.
Observe that the GoAccess dashboard is now empty and all previous data is gone.

4. Actual Behavior
The private IP addresses are clearly visible in the dashboard, indicating that --exclude-ip is being ignored.
All GoAccess statistics are reset to zero after a container restart.

5.  Expected Behavior
Any traffic from the IP ranges defined in GOACLA (e.g., 192.168.0.0/16) should be completely excluded from the GoAccess report.
Statistics should be persistent across container restarts, saved to the /data/goaccess/data directory, which is mapped to a host volume.
