### ISSUE TITLE
MariaDB / MySQL support? 

### ISSUE THREAD

**Issue by kokomo123** [ZoeyVid/NPMplus#293]
In the original project, there's MariaDB support and when I add the environmental variables, this fork container still uses SQLite, is there a plan for a environmental variable to disable SQLite and use Mariadb instead / PostgreSQL, etc?

**Comment by Zoey2936** [comment]
That's interesting, I didn't change the code in a way that MariaDB shouldn't work, let me take a look.

**Comment by kokomo123** [comment]
Thank you, because when i had them both in there, it didn't said using mysql support for whatever reason

**Comment by Zoey2936** [comment]
did you removed the npm config file and the database file?

**Comment by kokomo123** [comment]
No, so i could just try that again, ill let you know how it goes!
EDIT: Confirmed, I started with a brand new folder, the database has been created but no tables show up. All i get from NPM is "Using Sqlite: /data/etc/npm/database.sqlite" 
My docker-compose is here: app:
```yaml
   container_name: nginx-proxy-manager
    image: 'zoeyvid/nginx-proxy-manager:develop'
    restart: unless-stopped
    network_mode: host
    environment:
    - "TZ=America/New_York"
      # Mysql/Maria connection parameters:
    - "DB_MYSQL_HOST: db"
    - "DB_MYSQL_PORT: 3306"
    - "DB_MYSQL_USER: npm"
    - "DB_MYSQL_PASSWORD: [RETRACTED]"
    - "DB_MYSQL_NAME: npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
    depends_on:
      - db
  db:
    container_name: npm-db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '[RETRACTED]'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: [RETRACTED]'
    volumes:
      - ./mysql:/var/lib/mysql
```
If you need proper formatting, let me know as i can just slap the file in as well.

**Comment by kokomo123** [comment]
Confirmed, I started with a brand new folder, the database has been created but no tables show up. All i get from NPM is "Using Sqlite: /data/etc/npm/database.sqlite"

**Comment by Zoey2936** [comment]
I think the problem could be that the npm can't read the database

**Comment by Zoey2936** [comment]
But one question, why do you prefer mariadb?

**Comment by kokomo123** [comment]
I'm open to whatever DB that's possible. I assume mariadb/mysql is the only one available for NPM to use, otherwise do you use another DB in this fork besides SQLite? Thanks for correcting my formatting oops along with that's weird that it can't read the database at all even though its present. I could add ipv4 addresses to make sure npm can find the db, otherwise im stumped.

**Comment by kokomo123** [comment]
This was a issue on my part, it's part of my docker-compose.yml that seems to be wrong formatting. Apologies for the confusion.

**Comment by Zoey2936** [comment]
so it works now?

**Comment by kokomo123** [comment]
Yep, now it recognizes the database fine, I'm just trying to see how to get things going afterwards.

**Comment by Zoey2936** [comment]
can you maybe provide the compsoe file for others?

**Comment by kokomo123** [comment]
Sure, I could throw a example compose in here. *Strongly encourage to use ipv4 addresses if npm doesnt connect to the db the first time*
```
  app:
    container_name: nginx-proxy-manager
    image: 'zoeyvid/nginx-proxy-manager:develop'
    restart: unless-stopped
    network_mode: host 
(Use ports with ipv4 addresses only)
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      TZ: "America/New_York"
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "randompassword"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest' (or use mysql, another mariadb container, etc)
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'randompassword'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'randompassword''
    volumes:
      - ./mysql:/var/lib/mysql
```
