### ISSUE TITLE
New container crash, never start.

### ISSUE THREAD

**Issue by imoize** [ZoeyVid/NPMplus#394]
My docker stack
```
version: "3.9"
services:
  npm:
    image: zoeyvid/nginx-proxy-manager:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
      - target: 81
        published: 8181
        protocol: tcp
        mode: host
      - target: 443
        published: 4443
        protocol: tcp
        mode: host
    volumes:
      - "/mnt/npm-test:/data"
    networks:
      - npm-test
    environment:
      - "TZ=Asia/Jakarta" # set timezone, required
      - "PUID=1000" # set group id, default 0 (root)
      - "PGID=1000" # set user id, default 0 (root)

networks:
  npm-test:
    name: npm-test
    driver: overlay
    external: false
```

Docker logs (only show this before container restarted):
```
----------------------------------------------------------
Let's Encrypt certificates cleanup - 2023/09/08 23:32:25
----------------------------------------------------------
0 file(s) kept.
0 file(s) deleted.
skipped '/data/etc/modsecurity/crs-setup.conf'
no NPM_CERT_ID set, using dummycerts for npm and default hosts.
Working on file: /data/nginx/custom/events.conf
Working on file: /data/nginx/custom/http.conf
Working on file: /data/nginx/custom/http_top.conf
Working on file: /data/nginx/custom/root.conf
Working on file: /data/nginx/custom/server_dead.conf
Working on file: /data/nginx/custom/server_proxy.conf
Working on file: /data/nginx/custom/server_redirect.conf
Working on file: /data/nginx/custom/server_stream.conf
Working on file: /data/nginx/custom/server_stream_tcp.conf
Working on file: /data/nginx/custom/server_stream_udp.conf
Working on file: /data/nginx/custom/stream.conf
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/ip_ranges.conf
Success.
-------------------------------------
 _   _ ____  __  __
| \ | |  _ \|  \/  |
|  \| | |_) | |\/| |
| |\  |  __/| |  | |
|_| \_|_|   |_|  |_|
-------------------------------------
Version:  2.10.4+c943ccd
Date:     Fri Sep  8 23:33:57 WIB 2023
User:     npm
PUID:     1000
User ID:  1000
PGID:     1000
Group ID: 1000
-------------------------------------
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
[Global   ] › ℹ  info      Using Sqlite: /data/etc/npm/database.sqlite
[Global   ] › ℹ  info      Creating a new JWT key pair...
```

I'm running docker in swarm mode, and deploy with `docker stack deploy` after created container keep failed and restarted.
