### ISSUE TITLE
Error loading in Firefox

### ISSUE THREAD

**Issue by saweater** [ZoeyVid/NPMplus#471]
Hey, the project is very cool.

After freshly installed NPMplus, I get error message MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING in Firefox. If I refresh several times, then the page comes up the fourth or fifth time. After that it works for a few minutes.
The error comes with the Admin UI or with the proxy hosts set up. It makes no difference if you use a Letsencrypt certificate or the dummycert.

My Compose File:

```
version: "3"
services:
    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        image: zoeyvid/nginx-proxy-manager:latest
        restart: always
        network_mode: host
        volumes:
        - "/nginx-proxy-manager/data:/data"
        - "TZ=Europe/Zurich"
        - "NPM_CERT_ID=1" # ID of cert, which should be used instead of dummycerts, default unset/dummycerts
        - "NGINX_LOG_NOT_FOUND=true" # Allow logging of 404 errors, default false
```
