### ISSUE TITLE
Nginx bind failure

### ISSUE THREAD

**Issue by pimpmyname2** [ZoeyVid/NPMplus#498]
**Description:**
Encountering bind failures in Nginx with error messages indicating address in use. This occurs during the restart process, as outlined in the provided images. Nginx restarts every hour to renew certificates, and it can do that approx. 6 times before it crashes. Other than that, it works perfectly.

**Images:**

![IMG_20231126_142130](https://github.com/ZoeyVid/NPMplus/assets/79339372/cd21a34a-a8b7-41e8-b47b-50025202618a)
![IMG_20231126_142202](https://github.com/ZoeyVid/NPMplus/assets/79339372/9535166e-ab8d-4aae-8c22-312c38568e71)
![IMG_20231126_142243](https://github.com/ZoeyVid/NPMplus/assets/79339372/14c1f56d-361f-4d2f-848e-2b42f2095246)

**Additional information:**
Container is running on image: zoeyvid/npmplus:latest
There isnt any other services besides of npmplus using port 80 and 443.

EDIT:
sysctl.conf:
```
net.ipv4.ip_forward=1
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv4.ip_unprivileged_port_start=0
```
docker-compose:
```
version: '3.8'
services:
  npmplus:
    image: zoeyvid/npmplus:latest
    restart: unless-stopped
    network_mode: host
    networks:
      - proxy
    volumes:
      - "/opt/npm:/data"
#      - "/var/www:/var/www" # optional, if you want to use it as webserver for html/php
#      - "/opt/npm-letsencrypt:/etc/letsencrypt" # Only needed for first time migration from original nginx-proxy-manager to this fork
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
      - 81:81
    environment:
      - "TZ=Europe/Oslo"
#      - "PUID=1000" # set group id, default 0 (root)
#      - "PGID=1000" # set user id, default 0 (root)
#      - "NIBEP=48694" # internal port, always bound to 127.0.0.1, default 48693, you need to change it, if you want to run multiple npm instances in network mode host
#      - "NPM_PORT=82" # Port the NPM backend should be bound to, default 81, you need to change it, if you want to run multiple npm instances in network mode host
#      - "IPV4_BINDING=127.0.0.1" # IPv4 address to bind, defaults to all
#      - "NPM_IPV4_BINDING=127.0.0.1" # IPv4 address to bind for the NPM backend, defaults to all
#      - "IPV6_BINDING=[::1]" # IPv6 address to bind, defaults to all
#      - "NPM_IPV6_BINDING=[::1]" # IPv6 address to bind for the NPM backend, defaults to all
      - "DISABLE_IPV6=true" # disable IPv6, overrides with IPV6_BINDING, default false
      - "NPM_DISABLE_IPV6=true" # disable IPv6 for the NPM backend, overrides with NPM_IPV6_BINDING, default false, overrides NPM_LISTEN_LOCALHOST
#      - "NPM_LISTEN_LOCALHOST=true" # Bind the NPM Dashboard on Port 81 only to localhost, overrides with NPM_IPV4_BINDING/NPM_IPV6_BINDING, default false
      - "NPM_CERT_ID=2" # ID of cert, which should be used instead of dummycerts, default 0/unset/dummycerts
#      - "DISABLE_HTTP=true" # disables nginx to listen on port 80, default false
#      - "NGINX_LOG_NOT_FOUND=true" # Allow logging of 404 errors, default false
#      - "CLEAN=false" # Clean folders, default true
#      - "FULLCLEAN=true" # Clean unused config folders, default false
#      - "PHP81=true" # Activate PHP81, default false
#      - "PHP81_APKS=php81-curl php-81-curl" # Add php extensions, see available packages here: https://pkgs.alpinelinux.org/packages?branch=v3.18&repo=community&arch=x86_64&name=php81-*, default none
#      - "PHP82=true" # Activate PHP82, default false
#      - "PHP82_APKS=php82-curl php-82-curl" # Add php extensions, see available packages here: https://pkgs.alpinelinux.org/packages?branch=v3.18&repo=community&arch=x86_64&name=php82-*, default none

networks:
  proxy:
    external: true
```
